#pragma checksum "..\src\FocusApp.Desktop\MainWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "37E4B352E307332196A20F41E3CDD7E30FED15D8"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FocusApp.Desktop.ViewModels;
using FocusApp.Desktop.Views;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FocusApp.Desktop {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 110 "..\src\FocusApp.Desktop\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton AccountButton;
        
        #line default
        #line hidden
        
        
        #line 211 "..\src\FocusApp.Desktop\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup GuestLoginHintPopup;
        
        #line default
        #line hidden
        
        
        #line 217 "..\src\FocusApp.Desktop\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GuestLoginHintRoot;
        
        #line default
        #line hidden
        
        
        #line 269 "..\src\FocusApp.Desktop\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ThemeButton;
        
        #line default
        #line hidden
        
        
        #line 301 "..\src\FocusApp.Desktop\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ContentControl PageHost;
        
        #line default
        #line hidden
        
        
        #line 425 "..\src\FocusApp.Desktop\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FocusApp.Desktop.Views.CustomTimeModal CustomTimeModalControl;
        
        #line default
        #line hidden
        
        
        #line 444 "..\src\FocusApp.Desktop\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FocusApp.Desktop.Views.ThemePanel ThemePanelControl;
        
        #line default
        #line hidden
        
        
        #line 464 "..\src\FocusApp.Desktop\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FocusApp.Desktop.Views.AccountPanel AccountPanelControl;
        
        #line default
        #line hidden
        
        
        #line 834 "..\src\FocusApp.Desktop\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid FocusResultToastOverlay;
        
        #line default
        #line hidden
        
        
        #line 960 "..\src\FocusApp.Desktop\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FocusApp.Desktop.Views.CreateGoalModal CreateGoalModalControl;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/FocusApp.Desktop;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\src\FocusApp.Desktop\MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 14 "..\src\FocusApp.Desktop\MainWindow.xaml"
            ((FocusApp.Desktop.MainWindow)(target)).PreviewMouseDown += new System.Windows.Input.MouseButtonEventHandler(this.Window_PreviewMouseDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.AccountButton = ((System.Windows.Controls.RadioButton)(target));
            
            #line 120 "..\src\FocusApp.Desktop\MainWindow.xaml"
            this.AccountButton.MouseEnter += new System.Windows.Input.MouseEventHandler(this.GuestAccountHint_MouseEnter);
            
            #line default
            #line hidden
            
            #line 121 "..\src\FocusApp.Desktop\MainWindow.xaml"
            this.AccountButton.MouseLeave += new System.Windows.Input.MouseEventHandler(this.GuestAccountHint_MouseLeave);
            
            #line default
            #line hidden
            
            #line 122 "..\src\FocusApp.Desktop\MainWindow.xaml"
            this.AccountButton.PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.AccountButton_PreviewMouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 3:
            this.GuestLoginHintPopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 4:
            this.GuestLoginHintRoot = ((System.Windows.Controls.Grid)(target));
            
            #line 221 "..\src\FocusApp.Desktop\MainWindow.xaml"
            this.GuestLoginHintRoot.MouseEnter += new System.Windows.Input.MouseEventHandler(this.GuestAccountHint_MouseEnter);
            
            #line default
            #line hidden
            
            #line 222 "..\src\FocusApp.Desktop\MainWindow.xaml"
            this.GuestLoginHintRoot.MouseLeave += new System.Windows.Input.MouseEventHandler(this.GuestAccountHint_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 5:
            
            #line 265 "..\src\FocusApp.Desktop\MainWindow.xaml"
            ((System.Windows.Controls.Grid)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.TitleBar_MouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 6:
            this.ThemeButton = ((System.Windows.Controls.Button)(target));
            
            #line 271 "..\src\FocusApp.Desktop\MainWindow.xaml"
            this.ThemeButton.Click += new System.Windows.RoutedEventHandler(this.ThemeButton_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            
            #line 280 "..\src\FocusApp.Desktop\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.MinimizeButton_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            
            #line 289 "..\src\FocusApp.Desktop\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CloseButton_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.PageHost = ((System.Windows.Controls.ContentControl)(target));
            return;
            case 10:
            
            #line 336 "..\src\FocusApp.Desktop\MainWindow.xaml"
            ((System.Windows.Controls.Border)(target)).MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.WebsiteScrim_MouseDown);
            
            #line default
            #line hidden
            return;
            case 11:
            
            #line 343 "..\src\FocusApp.Desktop\MainWindow.xaml"
            ((System.Windows.Controls.Border)(target)).MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.ProgramScrim_MouseDown);
            
            #line default
            #line hidden
            return;
            case 12:
            
            #line 350 "..\src\FocusApp.Desktop\MainWindow.xaml"
            ((System.Windows.Controls.Border)(target)).MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.BlockedContentScrim_MouseDown);
            
            #line default
            #line hidden
            return;
            case 13:
            
            #line 368 "..\src\FocusApp.Desktop\MainWindow.xaml"
            ((System.Windows.Controls.Border)(target)).MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.AuthScrim_MouseDown);
            
            #line default
            #line hidden
            return;
            case 14:
            
            #line 386 "..\src\FocusApp.Desktop\MainWindow.xaml"
            ((System.Windows.Controls.Border)(target)).MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.RuleScrim_MouseDown);
            
            #line default
            #line hidden
            return;
            case 15:
            
            #line 406 "..\src\FocusApp.Desktop\MainWindow.xaml"
            ((System.Windows.Controls.Border)(target)).MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.RuleActivationScrim_MouseDown);
            
            #line default
            #line hidden
            return;
            case 16:
            this.CustomTimeModalControl = ((FocusApp.Desktop.Views.CustomTimeModal)(target));
            return;
            case 17:
            this.ThemePanelControl = ((FocusApp.Desktop.Views.ThemePanel)(target));
            return;
            case 18:
            this.AccountPanelControl = ((FocusApp.Desktop.Views.AccountPanel)(target));
            return;
            case 19:
            
            #line 482 "..\src\FocusApp.Desktop\MainWindow.xaml"
            ((System.Windows.Controls.Border)(target)).MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.FocusTargetScrim_MouseDown);
            
            #line default
            #line hidden
            return;
            case 20:
            
            #line 501 "..\src\FocusApp.Desktop\MainWindow.xaml"
            ((System.Windows.Controls.Border)(target)).MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.VipScrim_MouseDown);
            
            #line default
            #line hidden
            return;
            case 21:
            
            #line 520 "..\src\FocusApp.Desktop\MainWindow.xaml"
            ((System.Windows.Controls.Border)(target)).MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.AccountSyncScrim_MouseDown);
            
            #line default
            #line hidden
            return;
            case 22:
            
            #line 539 "..\src\FocusApp.Desktop\MainWindow.xaml"
            ((System.Windows.Controls.Border)(target)).MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.MembershipCenterScrim_MouseDown);
            
            #line default
            #line hidden
            return;
            case 23:
            
            #line 558 "..\src\FocusApp.Desktop\MainWindow.xaml"
            ((System.Windows.Controls.Border)(target)).MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.ExportRecordsScrim_MouseDown);
            
            #line default
            #line hidden
            return;
            case 24:
            
            #line 577 "..\src\FocusApp.Desktop\MainWindow.xaml"
            ((System.Windows.Controls.Border)(target)).MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.FocusGoalSettingsScrim_MouseDown);
            
            #line default
            #line hidden
            return;
            case 25:
            this.FocusResultToastOverlay = ((System.Windows.Controls.Grid)(target));
            return;
            case 26:
            this.CreateGoalModalControl = ((FocusApp.Desktop.Views.CreateGoalModal)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

