#pragma checksum "..\..\src\FocusApp.Desktop\Views\ExportRecordsModal.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "7766BB00171D67011C1DC56A19E6D9415F320E91"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FocusApp.Desktop.Views {
    
    
    /// <summary>
    /// ExportRecordsModal
    /// </summary>
    public partial class ExportRecordsModal : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 207 "..\..\src\FocusApp.Desktop\Views\ExportRecordsModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button TimeRangeOptionButton;
        
        #line default
        #line hidden
        
        
        #line 233 "..\..\src\FocusApp.Desktop\Views\ExportRecordsModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button IncludedContentOptionButton;
        
        #line default
        #line hidden
        
        
        #line 259 "..\..\src\FocusApp.Desktop\Views\ExportRecordsModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup TimeRangePopup;
        
        #line default
        #line hidden
        
        
        #line 282 "..\..\src\FocusApp.Desktop\Views\ExportRecordsModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup IncludedContentPopup;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/FocusApp.Desktop;component/views/exportrecordsmodal.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\src\FocusApp.Desktop\Views\ExportRecordsModal.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.TimeRangeOptionButton = ((System.Windows.Controls.Button)(target));
            return;
            case 2:
            this.IncludedContentOptionButton = ((System.Windows.Controls.Button)(target));
            return;
            case 3:
            this.TimeRangePopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 4:
            this.IncludedContentPopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

