#pragma checksum "..\..\src\FocusApp.Desktop\Views\FocusTaskWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "EFC806EF097A424B97DC7A2F6384DCAA569F590B"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FocusApp.Desktop.Views;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FocusApp.Desktop.Views {
    
    
    /// <summary>
    /// FocusTaskWindow
    /// </summary>
    public partial class FocusTaskWindow : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 220 "..\..\src\FocusApp.Desktop\Views\FocusTaskWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer TaskListScrollViewer;
        
        #line default
        #line hidden
        
        
        #line 232 "..\..\src\FocusApp.Desktop\Views\FocusTaskWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl PendingTaskList;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/FocusApp.Desktop;component/views/focustaskwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\src\FocusApp.Desktop\Views\FocusTaskWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 8 "..\..\src\FocusApp.Desktop\Views\FocusTaskWindow.xaml"
            ((FocusApp.Desktop.Views.FocusTaskWindow)(target)).PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.FocusTaskWindow_PreviewKeyDown);
            
            #line default
            #line hidden
            return;
            case 2:
            
            #line 191 "..\..\src\FocusApp.Desktop\Views\FocusTaskWindow.xaml"
            ((System.Windows.Controls.Border)(target)).MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.Window_MouseDown);
            
            #line default
            #line hidden
            return;
            case 3:
            
            #line 214 "..\..\src\FocusApp.Desktop\Views\FocusTaskWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CloseButton_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.TaskListScrollViewer = ((System.Windows.Controls.ScrollViewer)(target));
            
            #line 224 "..\..\src\FocusApp.Desktop\Views\FocusTaskWindow.xaml"
            this.TaskListScrollViewer.DragOver += new System.Windows.DragEventHandler(this.TaskList_DragOver);
            
            #line default
            #line hidden
            
            #line 225 "..\..\src\FocusApp.Desktop\Views\FocusTaskWindow.xaml"
            this.TaskListScrollViewer.Drop += new System.Windows.DragEventHandler(this.TaskList_Drop);
            
            #line default
            #line hidden
            return;
            case 5:
            this.PendingTaskList = ((System.Windows.Controls.ItemsControl)(target));
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 6:
            
            #line 239 "..\..\src\FocusApp.Desktop\Views\FocusTaskWindow.xaml"
            ((System.Windows.Controls.Grid)(target)).PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.PendingTaskList_PreviewMouseLeftButtonDown);
            
            #line default
            #line hidden
            
            #line 240 "..\..\src\FocusApp.Desktop\Views\FocusTaskWindow.xaml"
            ((System.Windows.Controls.Grid)(target)).PreviewMouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.PendingTaskList_PreviewMouseLeftButtonUp);
            
            #line default
            #line hidden
            
            #line 241 "..\..\src\FocusApp.Desktop\Views\FocusTaskWindow.xaml"
            ((System.Windows.Controls.Grid)(target)).PreviewMouseMove += new System.Windows.Input.MouseEventHandler(this.PendingTaskList_PreviewMouseMove);
            
            #line default
            #line hidden
            break;
            case 7:
            
            #line 272 "..\..\src\FocusApp.Desktop\Views\FocusTaskWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CompleteTask_Click);
            
            #line default
            #line hidden
            break;
            case 8:
            
            #line 276 "..\..\src\FocusApp.Desktop\Views\FocusTaskWindow.xaml"
            ((System.Windows.Controls.TextBox)(target)).IsVisibleChanged += new System.Windows.DependencyPropertyChangedEventHandler(this.Editor_IsVisibleChanged);
            
            #line default
            #line hidden
            
            #line 277 "..\..\src\FocusApp.Desktop\Views\FocusTaskWindow.xaml"
            ((System.Windows.Controls.TextBox)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Editor_Loaded);
            
            #line default
            #line hidden
            
            #line 278 "..\..\src\FocusApp.Desktop\Views\FocusTaskWindow.xaml"
            ((System.Windows.Controls.TextBox)(target)).LostKeyboardFocus += new System.Windows.Input.KeyboardFocusChangedEventHandler(this.TargetTaskTextBox_LostKeyboardFocus);
            
            #line default
            #line hidden
            break;
            case 9:
            
            #line 447 "..\..\src\FocusApp.Desktop\Views\FocusTaskWindow.xaml"
            ((System.Windows.Controls.Grid)(target)).PreviewMouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.CompletedTaskRow_PreviewMouseLeftButtonUp);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

