#pragma checksum "..\..\src\FocusApp.Desktop\Views\FocusFloatingWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "43B7EE35863697E3B15C8337D2296C3AB772B9FA"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FocusApp.Desktop.Views;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FocusApp.Desktop.Views {
    
    
    /// <summary>
    /// FocusFloatingWindow
    /// </summary>
    public partial class FocusFloatingWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 20 "..\..\src\FocusApp.Desktop\Views\FocusFloatingWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid ContentHost;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\src\FocusApp.Desktop\Views\FocusFloatingWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.TranslateTransform ContentTranslateTransform;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\src\FocusApp.Desktop\Views\FocusFloatingWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FocusApp.Desktop.Views.FloatingContent FloatingContentView;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\src\FocusApp.Desktop\Views\FocusFloatingWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FocusApp.Desktop.Views.FoldedHorizontal FoldedHorizontalView;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\src\FocusApp.Desktop\Views\FocusFloatingWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FocusApp.Desktop.Views.FoldedVertical FoldedVerticalView;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/FocusApp.Desktop;component/views/focusfloatingwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\src\FocusApp.Desktop\Views\FocusFloatingWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 15 "..\..\src\FocusApp.Desktop\Views\FocusFloatingWindow.xaml"
            ((FocusApp.Desktop.Views.FocusFloatingWindow)(target)).PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.Window_PreviewMouseLeftButtonDown);
            
            #line default
            #line hidden
            
            #line 16 "..\..\src\FocusApp.Desktop\Views\FocusFloatingWindow.xaml"
            ((FocusApp.Desktop.Views.FocusFloatingWindow)(target)).MouseEnter += new System.Windows.Input.MouseEventHandler(this.Window_MouseEnter);
            
            #line default
            #line hidden
            
            #line 17 "..\..\src\FocusApp.Desktop\Views\FocusFloatingWindow.xaml"
            ((FocusApp.Desktop.Views.FocusFloatingWindow)(target)).MouseLeave += new System.Windows.Input.MouseEventHandler(this.Window_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 2:
            this.ContentHost = ((System.Windows.Controls.Grid)(target));
            return;
            case 3:
            this.ContentTranslateTransform = ((System.Windows.Media.TranslateTransform)(target));
            return;
            case 4:
            this.FloatingContentView = ((FocusApp.Desktop.Views.FloatingContent)(target));
            return;
            case 5:
            this.FoldedHorizontalView = ((FocusApp.Desktop.Views.FoldedHorizontal)(target));
            return;
            case 6:
            this.FoldedVerticalView = ((FocusApp.Desktop.Views.FoldedVertical)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

