#pragma checksum "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "FD42680E1B36957DF3FBEB07483832BD96F95DCD"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FocusApp.Desktop.ViewModels;
using FocusApp.Desktop.Views;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FocusApp.Desktop.Views {
    
    
    /// <summary>
    /// StatisticsPage
    /// </summary>
    public partial class StatisticsPage : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 397 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border TodayStatisticsCard;
        
        #line default
        #line hidden
        
        
        #line 411 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel TodayFocusSecondaryInfo;
        
        #line default
        #line hidden
        
        
        #line 423 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SetTodayFocusTargetButton;
        
        #line default
        #line hidden
        
        
        #line 440 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border TrendCard;
        
        #line default
        #line hidden
        
        
        #line 442 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid VipTrendContent;
        
        #line default
        #line hidden
        
        
        #line 455 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel TrendSummaryHeader;
        
        #line default
        #line hidden
        
        
        #line 501 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FocusApp.Desktop.Views.TrendChart TrendChartControl;
        
        #line default
        #line hidden
        
        
        #line 506 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid VipLockedPlaceholder;
        
        #line default
        #line hidden
        
        
        #line 521 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border TrendVipHoverTarget;
        
        #line default
        #line hidden
        
        
        #line 531 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid LockedTrendSkeletonChart;
        
        #line default
        #line hidden
        
        
        #line 568 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup TrendVipGuidePopup;
        
        #line default
        #line hidden
        
        
        #line 620 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border MonthlyFocusTargetCard;
        
        #line default
        #line hidden
        
        
        #line 622 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid MonthlyFocusTargetEmptyState;
        
        #line default
        #line hidden
        
        
        #line 635 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SetMonthlyFocusTargetButton;
        
        #line default
        #line hidden
        
        
        #line 641 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid MonthlyFocusTargetSetState;
        
        #line default
        #line hidden
        
        
        #line 669 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ProgressBar MonthlyFocusTargetProgressBar;
        
        #line default
        #line hidden
        
        
        #line 677 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock MonthlyFocusTargetPercent;
        
        #line default
        #line hidden
        
        
        #line 709 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button EditMonthlyFocusTargetButton;
        
        #line default
        #line hidden
        
        
        #line 727 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup MonthlyFocusTargetActionMenu;
        
        #line default
        #line hidden
        
        
        #line 754 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border CalendarAndDistributionContainer;
        
        #line default
        #line hidden
        
        
        #line 894 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl GoalDistributionItemsControl;
        
        #line default
        #line hidden
        
        
        #line 1013 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border DailyFocusRecordCard;
        
        #line default
        #line hidden
        
        
        #line 1015 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid DailyFocusRecordContent;
        
        #line default
        #line hidden
        
        
        #line 1034 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid CalendarDayMetrics;
        
        #line default
        #line hidden
        
        
        #line 1065 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.ToggleButton CompletedTasksButton;
        
        #line default
        #line hidden
        
        
        #line 1118 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup CompletedTasksPopup;
        
        #line default
        #line hidden
        
        
        #line 1125 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CompletedTasksEmpty;
        
        #line default
        #line hidden
        
        
        #line 1126 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer CompletedTasksListScroll;
        
        #line default
        #line hidden
        
        
        #line 1164 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl CompletedTasksList;
        
        #line default
        #line hidden
        
        
        #line 1185 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer DailyDistributionScrollViewer;
        
        #line default
        #line hidden
        
        
        #line 1209 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer CalendarRecordsScrollViewer;
        
        #line default
        #line hidden
        
        
        #line 1267 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid DailyFocusRecordLockedPlaceholder;
        
        #line default
        #line hidden
        
        
        #line 1286 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border DailyFocusRecordVipHoverTarget;
        
        #line default
        #line hidden
        
        
        #line 1309 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer DailyFocusRecordLockedScrollViewer;
        
        #line default
        #line hidden
        
        
        #line 1357 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup DailyFocusRecordVipGuidePopup;
        
        #line default
        #line hidden
        
        
        #line 1409 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel GoalsPageLayout;
        
        #line default
        #line hidden
        
        
        #line 1415 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button GoalListMenuButton;
        
        #line default
        #line hidden
        
        
        #line 1487 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border GoalInvestmentDetailsCard;
        
        #line default
        #line hidden
        
        
        #line 1489 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GoalInvestmentDetailsContent;
        
        #line default
        #line hidden
        
        
        #line 1498 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.ToggleButton GoalDetailMoreButton;
        
        #line default
        #line hidden
        
        
        #line 1499 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup GoalDetailMorePopup;
        
        #line default
        #line hidden
        
        
        #line 1530 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer GoalProgressScrollViewer;
        
        #line default
        #line hidden
        
        
        #line 1532 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl GoalDateGroupsControl;
        
        #line default
        #line hidden
        
        
        #line 1583 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GoalInvestmentDetailsLockedPlaceholder;
        
        #line default
        #line hidden
        
        
        #line 1586 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border GoalInvestmentDetailsVipHoverTarget;
        
        #line default
        #line hidden
        
        
        #line 1593 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup GoalInvestmentDetailsVipGuidePopup;
        
        #line default
        #line hidden
        
        
        #line 1647 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup TrendTooltipPopup;
        
        #line default
        #line hidden
        
        
        #line 1675 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup GoalTrendTooltipPopup;
        
        #line default
        #line hidden
        
        
        #line 1713 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup MonthlyFocusTargetPopup;
        
        #line default
        #line hidden
        
        
        #line 1730 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox MonthlyFocusTargetInputBox;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/FocusApp.Desktop;component/views/statisticspage.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.TodayStatisticsCard = ((System.Windows.Controls.Border)(target));
            return;
            case 2:
            this.TodayFocusSecondaryInfo = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 3:
            this.SetTodayFocusTargetButton = ((System.Windows.Controls.Button)(target));
            return;
            case 4:
            this.TrendCard = ((System.Windows.Controls.Border)(target));
            return;
            case 5:
            this.VipTrendContent = ((System.Windows.Controls.Grid)(target));
            return;
            case 6:
            this.TrendSummaryHeader = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 7:
            this.TrendChartControl = ((FocusApp.Desktop.Views.TrendChart)(target));
            return;
            case 8:
            this.VipLockedPlaceholder = ((System.Windows.Controls.Grid)(target));
            return;
            case 9:
            this.TrendVipHoverTarget = ((System.Windows.Controls.Border)(target));
            
            #line 521 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.TrendVipHoverTarget.MouseEnter += new System.Windows.Input.MouseEventHandler(this.TrendVipHoverTarget_MouseEnter);
            
            #line default
            #line hidden
            
            #line 521 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.TrendVipHoverTarget.MouseLeave += new System.Windows.Input.MouseEventHandler(this.TrendVipHoverTarget_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 10:
            this.LockedTrendSkeletonChart = ((System.Windows.Controls.Grid)(target));
            return;
            case 11:
            this.TrendVipGuidePopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 12:
            
            #line 584 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Border)(target)).MouseEnter += new System.Windows.Input.MouseEventHandler(this.TrendVipGuide_MouseEnter);
            
            #line default
            #line hidden
            
            #line 585 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeave += new System.Windows.Input.MouseEventHandler(this.TrendVipGuide_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 13:
            
            #line 602 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.TrendVipGuideOpenButton_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            this.MonthlyFocusTargetCard = ((System.Windows.Controls.Border)(target));
            return;
            case 15:
            this.MonthlyFocusTargetEmptyState = ((System.Windows.Controls.Grid)(target));
            return;
            case 16:
            this.SetMonthlyFocusTargetButton = ((System.Windows.Controls.Button)(target));
            
            #line 635 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.SetMonthlyFocusTargetButton.PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.MonthlyFocusTargetAnchor_PreviewMouseLeftButtonDown);
            
            #line default
            #line hidden
            
            #line 635 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.SetMonthlyFocusTargetButton.Click += new System.Windows.RoutedEventHandler(this.SetMonthlyFocusTargetButton_Click);
            
            #line default
            #line hidden
            return;
            case 17:
            this.MonthlyFocusTargetSetState = ((System.Windows.Controls.Grid)(target));
            return;
            case 18:
            this.MonthlyFocusTargetProgressBar = ((System.Windows.Controls.ProgressBar)(target));
            return;
            case 19:
            this.MonthlyFocusTargetPercent = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 20:
            this.EditMonthlyFocusTargetButton = ((System.Windows.Controls.Button)(target));
            
            #line 725 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.EditMonthlyFocusTargetButton.PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.MonthlyFocusTargetMenuButton_PreviewMouseLeftButtonDown);
            
            #line default
            #line hidden
            
            #line 726 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.EditMonthlyFocusTargetButton.Click += new System.Windows.RoutedEventHandler(this.MonthlyFocusTargetMenuButton_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            this.MonthlyFocusTargetActionMenu = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 22:
            
            #line 740 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.EditMonthlyFocusTargetMenuItem_Click);
            
            #line default
            #line hidden
            return;
            case 23:
            
            #line 741 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.DeleteMonthlyFocusTargetMenuItem_Click);
            
            #line default
            #line hidden
            return;
            case 24:
            this.CalendarAndDistributionContainer = ((System.Windows.Controls.Border)(target));
            return;
            case 25:
            this.GoalDistributionItemsControl = ((System.Windows.Controls.ItemsControl)(target));
            return;
            case 26:
            this.DailyFocusRecordCard = ((System.Windows.Controls.Border)(target));
            return;
            case 27:
            this.DailyFocusRecordContent = ((System.Windows.Controls.Grid)(target));
            return;
            case 28:
            this.CalendarDayMetrics = ((System.Windows.Controls.Grid)(target));
            return;
            case 29:
            this.CompletedTasksButton = ((System.Windows.Controls.Primitives.ToggleButton)(target));
            
            #line 1065 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.CompletedTasksButton.PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.CompletedTasks_PreviewMouseLeftButtonDown);
            
            #line default
            #line hidden
            
            #line 1065 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.CompletedTasksButton.Click += new System.Windows.RoutedEventHandler(this.CompletedTasks_Click);
            
            #line default
            #line hidden
            return;
            case 30:
            this.CompletedTasksPopup = ((System.Windows.Controls.Primitives.Popup)(target));
            
            #line 1118 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.CompletedTasksPopup.Closed += new System.EventHandler(this.CompletedTasksPopup_Closed);
            
            #line default
            #line hidden
            return;
            case 31:
            
            #line 1119 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Border)(target)).KeyDown += new System.Windows.Input.KeyEventHandler(this.CompletedTasksPopup_KeyDown);
            
            #line default
            #line hidden
            return;
            case 32:
            this.CompletedTasksEmpty = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 33:
            this.CompletedTasksListScroll = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 34:
            this.CompletedTasksList = ((System.Windows.Controls.ItemsControl)(target));
            return;
            case 35:
            this.DailyDistributionScrollViewer = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 36:
            this.CalendarRecordsScrollViewer = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 38:
            this.DailyFocusRecordLockedPlaceholder = ((System.Windows.Controls.Grid)(target));
            return;
            case 39:
            this.DailyFocusRecordVipHoverTarget = ((System.Windows.Controls.Border)(target));
            
            #line 1289 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.DailyFocusRecordVipHoverTarget.MouseEnter += new System.Windows.Input.MouseEventHandler(this.DailyFocusRecordVipHoverTarget_MouseEnter);
            
            #line default
            #line hidden
            
            #line 1290 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.DailyFocusRecordVipHoverTarget.MouseLeave += new System.Windows.Input.MouseEventHandler(this.DailyFocusRecordVipHoverTarget_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 40:
            this.DailyFocusRecordLockedScrollViewer = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 41:
            this.DailyFocusRecordVipGuidePopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 42:
            
            #line 1373 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Border)(target)).MouseEnter += new System.Windows.Input.MouseEventHandler(this.DailyFocusRecordVipGuide_MouseEnter);
            
            #line default
            #line hidden
            
            #line 1374 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeave += new System.Windows.Input.MouseEventHandler(this.DailyFocusRecordVipGuide_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 43:
            
            #line 1391 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.DailyFocusRecordVipGuideOpenButton_Click);
            
            #line default
            #line hidden
            return;
            case 44:
            this.GoalsPageLayout = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 45:
            this.GoalListMenuButton = ((System.Windows.Controls.Button)(target));
            return;
            case 46:
            
            #line 1427 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SelectCurrentGoalListButton_Click);
            
            #line default
            #line hidden
            return;
            case 47:
            
            #line 1430 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SelectArchivedGoalListButton_Click);
            
            #line default
            #line hidden
            return;
            case 50:
            this.GoalInvestmentDetailsCard = ((System.Windows.Controls.Border)(target));
            return;
            case 51:
            this.GoalInvestmentDetailsContent = ((System.Windows.Controls.Grid)(target));
            return;
            case 52:
            this.GoalDetailMoreButton = ((System.Windows.Controls.Primitives.ToggleButton)(target));
            return;
            case 53:
            this.GoalDetailMorePopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 54:
            
            #line 1503 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.EditGoalButton_Click);
            
            #line default
            #line hidden
            return;
            case 55:
            
            #line 1504 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ArchiveGoalButton_Click);
            
            #line default
            #line hidden
            return;
            case 56:
            
            #line 1505 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.RestoreGoalButton_Click);
            
            #line default
            #line hidden
            return;
            case 57:
            
            #line 1506 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.DeleteGoalButton_Click);
            
            #line default
            #line hidden
            return;
            case 58:
            this.GoalProgressScrollViewer = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 59:
            this.GoalDateGroupsControl = ((System.Windows.Controls.ItemsControl)(target));
            return;
            case 61:
            this.GoalInvestmentDetailsLockedPlaceholder = ((System.Windows.Controls.Grid)(target));
            return;
            case 62:
            this.GoalInvestmentDetailsVipHoverTarget = ((System.Windows.Controls.Border)(target));
            
            #line 1586 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.GoalInvestmentDetailsVipHoverTarget.MouseEnter += new System.Windows.Input.MouseEventHandler(this.GoalInvestmentDetailsVipHoverTarget_MouseEnter);
            
            #line default
            #line hidden
            
            #line 1586 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.GoalInvestmentDetailsVipHoverTarget.MouseLeave += new System.Windows.Input.MouseEventHandler(this.GoalInvestmentDetailsVipHoverTarget_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 63:
            this.GoalInvestmentDetailsVipGuidePopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 64:
            
            #line 1609 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Border)(target)).MouseEnter += new System.Windows.Input.MouseEventHandler(this.GoalInvestmentDetailsVipGuide_MouseEnter);
            
            #line default
            #line hidden
            
            #line 1610 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeave += new System.Windows.Input.MouseEventHandler(this.GoalInvestmentDetailsVipGuide_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 65:
            
            #line 1627 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.GoalInvestmentDetailsVipGuideOpenButton_Click);
            
            #line default
            #line hidden
            return;
            case 66:
            this.TrendTooltipPopup = ((System.Windows.Controls.Primitives.Popup)(target));
            
            #line 1650 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.TrendTooltipPopup.Closed += new System.EventHandler(this.TrendTooltipPopup_Closed);
            
            #line default
            #line hidden
            
            #line 1654 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.TrendTooltipPopup.Opened += new System.EventHandler(this.TrendTooltipPopup_Opened);
            
            #line default
            #line hidden
            return;
            case 67:
            this.GoalTrendTooltipPopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 68:
            this.MonthlyFocusTargetPopup = ((System.Windows.Controls.Primitives.Popup)(target));
            
            #line 1719 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.MonthlyFocusTargetPopup.Opened += new System.EventHandler(this.MonthlyFocusTargetPopup_Opened);
            
            #line default
            #line hidden
            return;
            case 69:
            this.MonthlyFocusTargetInputBox = ((System.Windows.Controls.TextBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 37:
            
            #line 1216 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.FocusRecord_Click);
            
            #line default
            #line hidden
            break;
            case 48:
            
            #line 1460 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.TextBox)(target)).IsVisibleChanged += new System.Windows.DependencyPropertyChangedEventHandler(this.GoalNameTextBox_IsVisibleChanged);
            
            #line default
            #line hidden
            
            #line 1460 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.TextBox)(target)).LostKeyboardFocus += new System.Windows.Input.KeyboardFocusChangedEventHandler(this.GoalNameTextBox_LostKeyboardFocus);
            
            #line default
            #line hidden
            
            #line 1460 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.TextBox)(target)).PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.GoalNameTextBox_PreviewKeyDown);
            
            #line default
            #line hidden
            break;
            case 49:
            
            #line 1467 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SaveGoalRenameButton_Click);
            
            #line default
            #line hidden
            break;
            case 60:
            
            #line 1552 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.FocusRecord_Click);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

