#pragma checksum "..\..\src\FocusApp.Desktop\Views\AutomaticRuleModal.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "06984E3E85E8C21B8A87AB6CF8106A878ED85DBA"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FocusApp.Desktop.Views {
    
    
    /// <summary>
    /// AutomaticRuleModal
    /// </summary>
    public partial class AutomaticRuleModal : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 92 "..\..\src\FocusApp.Desktop\Views\AutomaticRuleModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer TimelineScroll;
        
        #line default
        #line hidden
        
        
        #line 101 "..\..\src\FocusApp.Desktop\Views\AutomaticRuleModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas Timeline;
        
        #line default
        #line hidden
        
        
        #line 105 "..\..\src\FocusApp.Desktop\Views\AutomaticRuleModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TimelineHint;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/FocusApp.Desktop;component/views/automaticrulemodal.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\src\FocusApp.Desktop\Views\AutomaticRuleModal.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 8 "..\..\src\FocusApp.Desktop\Views\AutomaticRuleModal.xaml"
            ((FocusApp.Desktop.Views.AutomaticRuleModal)(target)).Loaded += new System.Windows.RoutedEventHandler(this.OnLoaded);
            
            #line default
            #line hidden
            
            #line 8 "..\..\src\FocusApp.Desktop\Views\AutomaticRuleModal.xaml"
            ((FocusApp.Desktop.Views.AutomaticRuleModal)(target)).Unloaded += new System.Windows.RoutedEventHandler(this.OnUnloaded);
            
            #line default
            #line hidden
            
            #line 8 "..\..\src\FocusApp.Desktop\Views\AutomaticRuleModal.xaml"
            ((FocusApp.Desktop.Views.AutomaticRuleModal)(target)).PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.OnKeyDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.TimelineScroll = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 3:
            this.Timeline = ((System.Windows.Controls.Canvas)(target));
            
            #line 101 "..\..\src\FocusApp.Desktop\Views\AutomaticRuleModal.xaml"
            this.Timeline.SizeChanged += new System.Windows.SizeChangedEventHandler(this.Timeline_SizeChanged);
            
            #line default
            #line hidden
            
            #line 102 "..\..\src\FocusApp.Desktop\Views\AutomaticRuleModal.xaml"
            this.Timeline.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.Timeline_MouseDown);
            
            #line default
            #line hidden
            
            #line 102 "..\..\src\FocusApp.Desktop\Views\AutomaticRuleModal.xaml"
            this.Timeline.MouseMove += new System.Windows.Input.MouseEventHandler(this.Timeline_MouseMove);
            
            #line default
            #line hidden
            
            #line 102 "..\..\src\FocusApp.Desktop\Views\AutomaticRuleModal.xaml"
            this.Timeline.MouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.Timeline_MouseUp);
            
            #line default
            #line hidden
            
            #line 102 "..\..\src\FocusApp.Desktop\Views\AutomaticRuleModal.xaml"
            this.Timeline.LostMouseCapture += new System.Windows.Input.MouseEventHandler(this.Timeline_LostCapture);
            
            #line default
            #line hidden
            return;
            case 4:
            this.TimelineHint = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

