#pragma checksum "..\..\src\FocusApp.Desktop\Views\SettingsPage.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "6B27D5F5446086F51BD4EF392B32861FB5375862"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FocusApp.Desktop.Views {
    
    
    /// <summary>
    /// SettingsPage
    /// </summary>
    public partial class SettingsPage : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 2 "..\..\src\FocusApp.Desktop\Views\SettingsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FocusApp.Desktop.Views.SettingsPage SettingsPageRoot;
        
        #line default
        #line hidden
        
        
        #line 409 "..\..\src\FocusApp.Desktop\Views\SettingsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl AutomaticRulesList;
        
        #line default
        #line hidden
        
        
        #line 511 "..\..\src\FocusApp.Desktop\Views\SettingsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border ForcedModeVipHoverTarget;
        
        #line default
        #line hidden
        
        
        #line 531 "..\..\src\FocusApp.Desktop\Views\SettingsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup ForcedModeVipGuidePopup;
        
        #line default
        #line hidden
        
        
        #line 543 "..\..\src\FocusApp.Desktop\Views\SettingsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border ForcedModeVipGuideCard;
        
        #line default
        #line hidden
        
        
        #line 595 "..\..\src\FocusApp.Desktop\Views\SettingsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Polygon ForcedModeVipGuideTopArrow;
        
        #line default
        #line hidden
        
        
        #line 604 "..\..\src\FocusApp.Desktop\Views\SettingsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Polygon ForcedModeVipGuideBottomArrow;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/FocusApp.Desktop;component/views/settingspage.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\src\FocusApp.Desktop\Views\SettingsPage.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.SettingsPageRoot = ((FocusApp.Desktop.Views.SettingsPage)(target));
            return;
            case 2:
            this.AutomaticRulesList = ((System.Windows.Controls.ItemsControl)(target));
            return;
            case 7:
            this.ForcedModeVipHoverTarget = ((System.Windows.Controls.Border)(target));
            
            #line 518 "..\..\src\FocusApp.Desktop\Views\SettingsPage.xaml"
            this.ForcedModeVipHoverTarget.MouseEnter += new System.Windows.Input.MouseEventHandler(this.ForcedModeVipHoverTarget_MouseEnter);
            
            #line default
            #line hidden
            
            #line 519 "..\..\src\FocusApp.Desktop\Views\SettingsPage.xaml"
            this.ForcedModeVipHoverTarget.MouseLeave += new System.Windows.Input.MouseEventHandler(this.ForcedModeVipHoverTarget_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 8:
            this.ForcedModeVipGuidePopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 9:
            
            #line 541 "..\..\src\FocusApp.Desktop\Views\SettingsPage.xaml"
            ((System.Windows.Controls.Grid)(target)).MouseEnter += new System.Windows.Input.MouseEventHandler(this.ForcedModeVipGuide_MouseEnter);
            
            #line default
            #line hidden
            
            #line 542 "..\..\src\FocusApp.Desktop\Views\SettingsPage.xaml"
            ((System.Windows.Controls.Grid)(target)).MouseLeave += new System.Windows.Input.MouseEventHandler(this.ForcedModeVipGuide_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 10:
            this.ForcedModeVipGuideCard = ((System.Windows.Controls.Border)(target));
            return;
            case 11:
            this.ForcedModeVipGuideTopArrow = ((System.Windows.Shapes.Polygon)(target));
            return;
            case 12:
            this.ForcedModeVipGuideBottomArrow = ((System.Windows.Shapes.Polygon)(target));
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 3:
            
            #line 415 "..\..\src\FocusApp.Desktop\Views\SettingsPage.xaml"
            ((System.Windows.Controls.Border)(target)).MouseEnter += new System.Windows.Input.MouseEventHandler(this.AutomaticRuleRow_MouseEnter);
            
            #line default
            #line hidden
            break;
            case 4:
            
            #line 456 "..\..\src\FocusApp.Desktop\Views\SettingsPage.xaml"
            ((System.Windows.Controls.Primitives.ToggleButton)(target)).PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.RuleSwitch_PreviewMouseLeftButtonDown);
            
            #line default
            #line hidden
            break;
            case 5:
            
            #line 480 "..\..\src\FocusApp.Desktop\Views\SettingsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.RuleMenuItem_Click);
            
            #line default
            #line hidden
            break;
            case 6:
            
            #line 486 "..\..\src\FocusApp.Desktop\Views\SettingsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.RuleMenuItem_Click);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

