#pragma checksum "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "3EFAF18E19707BCB5DEB2C1776F8D9F0C7269930"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FocusApp.Desktop.ViewModels;
using FocusApp.Desktop.Views;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FocusApp.Desktop.Views {
    
    
    /// <summary>
    /// StatisticsPage
    /// </summary>
    public partial class StatisticsPage : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 407 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border TodayStatisticsCard;
        
        #line default
        #line hidden
        
        
        #line 409 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid TodayFocusEmptyState;
        
        #line default
        #line hidden
        
        
        #line 432 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel TodayFocusSecondaryInfo;
        
        #line default
        #line hidden
        
        
        #line 444 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SetTodayFocusTargetButton;
        
        #line default
        #line hidden
        
        
        #line 458 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid TodayFocusTargetState;
        
        #line default
        #line hidden
        
        
        #line 516 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border TrendCard;
        
        #line default
        #line hidden
        
        
        #line 518 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid VipTrendContent;
        
        #line default
        #line hidden
        
        
        #line 531 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel TrendSummaryHeader;
        
        #line default
        #line hidden
        
        
        #line 577 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FocusApp.Desktop.Views.TrendChart TrendChartControl;
        
        #line default
        #line hidden
        
        
        #line 582 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid VipLockedPlaceholder;
        
        #line default
        #line hidden
        
        
        #line 597 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border TrendVipHoverTarget;
        
        #line default
        #line hidden
        
        
        #line 607 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid LockedTrendSkeletonChart;
        
        #line default
        #line hidden
        
        
        #line 644 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup TrendVipGuidePopup;
        
        #line default
        #line hidden
        
        
        #line 696 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border MonthlyFocusTargetCard;
        
        #line default
        #line hidden
        
        
        #line 698 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid MonthlyFocusTargetEmptyState;
        
        #line default
        #line hidden
        
        
        #line 711 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SetMonthlyFocusTargetButton;
        
        #line default
        #line hidden
        
        
        #line 717 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid MonthlyFocusTargetSetState;
        
        #line default
        #line hidden
        
        
        #line 745 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ProgressBar MonthlyFocusTargetProgressBar;
        
        #line default
        #line hidden
        
        
        #line 753 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock MonthlyFocusTargetPercent;
        
        #line default
        #line hidden
        
        
        #line 785 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button EditMonthlyFocusTargetButton;
        
        #line default
        #line hidden
        
        
        #line 803 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup MonthlyFocusTargetActionMenu;
        
        #line default
        #line hidden
        
        
        #line 830 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border CalendarAndDistributionContainer;
        
        #line default
        #line hidden
        
        
        #line 970 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl GoalDistributionItemsControl;
        
        #line default
        #line hidden
        
        
        #line 1089 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border DailyFocusRecordCard;
        
        #line default
        #line hidden
        
        
        #line 1091 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid DailyFocusRecordContent;
        
        #line default
        #line hidden
        
        
        #line 1110 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid CalendarDayMetrics;
        
        #line default
        #line hidden
        
        
        #line 1141 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.ToggleButton CompletedTasksButton;
        
        #line default
        #line hidden
        
        
        #line 1194 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup CompletedTasksPopup;
        
        #line default
        #line hidden
        
        
        #line 1201 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CompletedTasksEmpty;
        
        #line default
        #line hidden
        
        
        #line 1202 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer CompletedTasksListScroll;
        
        #line default
        #line hidden
        
        
        #line 1240 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl CompletedTasksList;
        
        #line default
        #line hidden
        
        
        #line 1261 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer DailyDistributionScrollViewer;
        
        #line default
        #line hidden
        
        
        #line 1285 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer CalendarRecordsScrollViewer;
        
        #line default
        #line hidden
        
        
        #line 1343 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid DailyFocusRecordLockedPlaceholder;
        
        #line default
        #line hidden
        
        
        #line 1362 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border DailyFocusRecordVipHoverTarget;
        
        #line default
        #line hidden
        
        
        #line 1385 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer DailyFocusRecordLockedScrollViewer;
        
        #line default
        #line hidden
        
        
        #line 1433 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup DailyFocusRecordVipGuidePopup;
        
        #line default
        #line hidden
        
        
        #line 1485 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel GoalsPageLayout;
        
        #line default
        #line hidden
        
        
        #line 1491 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button GoalListMenuButton;
        
        #line default
        #line hidden
        
        
        #line 1563 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border GoalInvestmentDetailsCard;
        
        #line default
        #line hidden
        
        
        #line 1565 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GoalInvestmentDetailsContent;
        
        #line default
        #line hidden
        
        
        #line 1574 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.ToggleButton GoalDetailMoreButton;
        
        #line default
        #line hidden
        
        
        #line 1575 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup GoalDetailMorePopup;
        
        #line default
        #line hidden
        
        
        #line 1606 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer GoalProgressScrollViewer;
        
        #line default
        #line hidden
        
        
        #line 1608 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl GoalDateGroupsControl;
        
        #line default
        #line hidden
        
        
        #line 1659 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GoalInvestmentDetailsLockedPlaceholder;
        
        #line default
        #line hidden
        
        
        #line 1662 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border GoalInvestmentDetailsVipHoverTarget;
        
        #line default
        #line hidden
        
        
        #line 1669 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup GoalInvestmentDetailsVipGuidePopup;
        
        #line default
        #line hidden
        
        
        #line 1723 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup TrendTooltipPopup;
        
        #line default
        #line hidden
        
        
        #line 1751 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup GoalTrendTooltipPopup;
        
        #line default
        #line hidden
        
        
        #line 1789 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup MonthlyFocusTargetPopup;
        
        #line default
        #line hidden
        
        
        #line 1806 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox MonthlyFocusTargetInputBox;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/FocusApp.Desktop;component/views/statisticspage.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.TodayStatisticsCard = ((System.Windows.Controls.Border)(target));
            return;
            case 2:
            this.TodayFocusEmptyState = ((System.Windows.Controls.Grid)(target));
            return;
            case 3:
            this.TodayFocusSecondaryInfo = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 4:
            this.SetTodayFocusTargetButton = ((System.Windows.Controls.Button)(target));
            return;
            case 5:
            this.TodayFocusTargetState = ((System.Windows.Controls.Grid)(target));
            return;
            case 6:
            this.TrendCard = ((System.Windows.Controls.Border)(target));
            return;
            case 7:
            this.VipTrendContent = ((System.Windows.Controls.Grid)(target));
            return;
            case 8:
            this.TrendSummaryHeader = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 9:
            this.TrendChartControl = ((FocusApp.Desktop.Views.TrendChart)(target));
            return;
            case 10:
            this.VipLockedPlaceholder = ((System.Windows.Controls.Grid)(target));
            return;
            case 11:
            this.TrendVipHoverTarget = ((System.Windows.Controls.Border)(target));
            
            #line 597 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.TrendVipHoverTarget.MouseEnter += new System.Windows.Input.MouseEventHandler(this.TrendVipHoverTarget_MouseEnter);
            
            #line default
            #line hidden
            
            #line 597 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.TrendVipHoverTarget.MouseLeave += new System.Windows.Input.MouseEventHandler(this.TrendVipHoverTarget_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 12:
            this.LockedTrendSkeletonChart = ((System.Windows.Controls.Grid)(target));
            return;
            case 13:
            this.TrendVipGuidePopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 14:
            
            #line 660 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Border)(target)).MouseEnter += new System.Windows.Input.MouseEventHandler(this.TrendVipGuide_MouseEnter);
            
            #line default
            #line hidden
            
            #line 661 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeave += new System.Windows.Input.MouseEventHandler(this.TrendVipGuide_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 15:
            
            #line 678 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.TrendVipGuideOpenButton_Click);
            
            #line default
            #line hidden
            return;
            case 16:
            this.MonthlyFocusTargetCard = ((System.Windows.Controls.Border)(target));
            return;
            case 17:
            this.MonthlyFocusTargetEmptyState = ((System.Windows.Controls.Grid)(target));
            return;
            case 18:
            this.SetMonthlyFocusTargetButton = ((System.Windows.Controls.Button)(target));
            
            #line 711 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.SetMonthlyFocusTargetButton.PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.MonthlyFocusTargetAnchor_PreviewMouseLeftButtonDown);
            
            #line default
            #line hidden
            
            #line 711 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.SetMonthlyFocusTargetButton.Click += new System.Windows.RoutedEventHandler(this.SetMonthlyFocusTargetButton_Click);
            
            #line default
            #line hidden
            return;
            case 19:
            this.MonthlyFocusTargetSetState = ((System.Windows.Controls.Grid)(target));
            return;
            case 20:
            this.MonthlyFocusTargetProgressBar = ((System.Windows.Controls.ProgressBar)(target));
            return;
            case 21:
            this.MonthlyFocusTargetPercent = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 22:
            this.EditMonthlyFocusTargetButton = ((System.Windows.Controls.Button)(target));
            
            #line 801 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.EditMonthlyFocusTargetButton.PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.MonthlyFocusTargetMenuButton_PreviewMouseLeftButtonDown);
            
            #line default
            #line hidden
            
            #line 802 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.EditMonthlyFocusTargetButton.Click += new System.Windows.RoutedEventHandler(this.MonthlyFocusTargetMenuButton_Click);
            
            #line default
            #line hidden
            return;
            case 23:
            this.MonthlyFocusTargetActionMenu = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 24:
            
            #line 816 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.EditMonthlyFocusTargetMenuItem_Click);
            
            #line default
            #line hidden
            return;
            case 25:
            
            #line 817 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.DeleteMonthlyFocusTargetMenuItem_Click);
            
            #line default
            #line hidden
            return;
            case 26:
            this.CalendarAndDistributionContainer = ((System.Windows.Controls.Border)(target));
            return;
            case 27:
            this.GoalDistributionItemsControl = ((System.Windows.Controls.ItemsControl)(target));
            return;
            case 28:
            this.DailyFocusRecordCard = ((System.Windows.Controls.Border)(target));
            return;
            case 29:
            this.DailyFocusRecordContent = ((System.Windows.Controls.Grid)(target));
            return;
            case 30:
            this.CalendarDayMetrics = ((System.Windows.Controls.Grid)(target));
            return;
            case 31:
            this.CompletedTasksButton = ((System.Windows.Controls.Primitives.ToggleButton)(target));
            
            #line 1141 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.CompletedTasksButton.PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.CompletedTasks_PreviewMouseLeftButtonDown);
            
            #line default
            #line hidden
            
            #line 1141 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.CompletedTasksButton.Click += new System.Windows.RoutedEventHandler(this.CompletedTasks_Click);
            
            #line default
            #line hidden
            return;
            case 32:
            this.CompletedTasksPopup = ((System.Windows.Controls.Primitives.Popup)(target));
            
            #line 1194 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.CompletedTasksPopup.Closed += new System.EventHandler(this.CompletedTasksPopup_Closed);
            
            #line default
            #line hidden
            return;
            case 33:
            
            #line 1195 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Border)(target)).KeyDown += new System.Windows.Input.KeyEventHandler(this.CompletedTasksPopup_KeyDown);
            
            #line default
            #line hidden
            return;
            case 34:
            this.CompletedTasksEmpty = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 35:
            this.CompletedTasksListScroll = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 36:
            this.CompletedTasksList = ((System.Windows.Controls.ItemsControl)(target));
            return;
            case 37:
            this.DailyDistributionScrollViewer = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 38:
            this.CalendarRecordsScrollViewer = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 40:
            this.DailyFocusRecordLockedPlaceholder = ((System.Windows.Controls.Grid)(target));
            return;
            case 41:
            this.DailyFocusRecordVipHoverTarget = ((System.Windows.Controls.Border)(target));
            
            #line 1365 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.DailyFocusRecordVipHoverTarget.MouseEnter += new System.Windows.Input.MouseEventHandler(this.DailyFocusRecordVipHoverTarget_MouseEnter);
            
            #line default
            #line hidden
            
            #line 1366 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.DailyFocusRecordVipHoverTarget.MouseLeave += new System.Windows.Input.MouseEventHandler(this.DailyFocusRecordVipHoverTarget_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 42:
            this.DailyFocusRecordLockedScrollViewer = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 43:
            this.DailyFocusRecordVipGuidePopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 44:
            
            #line 1449 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Border)(target)).MouseEnter += new System.Windows.Input.MouseEventHandler(this.DailyFocusRecordVipGuide_MouseEnter);
            
            #line default
            #line hidden
            
            #line 1450 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeave += new System.Windows.Input.MouseEventHandler(this.DailyFocusRecordVipGuide_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 45:
            
            #line 1467 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.DailyFocusRecordVipGuideOpenButton_Click);
            
            #line default
            #line hidden
            return;
            case 46:
            this.GoalsPageLayout = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 47:
            this.GoalListMenuButton = ((System.Windows.Controls.Button)(target));
            return;
            case 48:
            
            #line 1503 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SelectCurrentGoalListButton_Click);
            
            #line default
            #line hidden
            return;
            case 49:
            
            #line 1506 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SelectArchivedGoalListButton_Click);
            
            #line default
            #line hidden
            return;
            case 52:
            this.GoalInvestmentDetailsCard = ((System.Windows.Controls.Border)(target));
            return;
            case 53:
            this.GoalInvestmentDetailsContent = ((System.Windows.Controls.Grid)(target));
            return;
            case 54:
            this.GoalDetailMoreButton = ((System.Windows.Controls.Primitives.ToggleButton)(target));
            return;
            case 55:
            this.GoalDetailMorePopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 56:
            
            #line 1579 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.EditGoalButton_Click);
            
            #line default
            #line hidden
            return;
            case 57:
            
            #line 1580 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ArchiveGoalButton_Click);
            
            #line default
            #line hidden
            return;
            case 58:
            
            #line 1581 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.RestoreGoalButton_Click);
            
            #line default
            #line hidden
            return;
            case 59:
            
            #line 1582 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.DeleteGoalButton_Click);
            
            #line default
            #line hidden
            return;
            case 60:
            this.GoalProgressScrollViewer = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 61:
            this.GoalDateGroupsControl = ((System.Windows.Controls.ItemsControl)(target));
            return;
            case 63:
            this.GoalInvestmentDetailsLockedPlaceholder = ((System.Windows.Controls.Grid)(target));
            return;
            case 64:
            this.GoalInvestmentDetailsVipHoverTarget = ((System.Windows.Controls.Border)(target));
            
            #line 1662 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.GoalInvestmentDetailsVipHoverTarget.MouseEnter += new System.Windows.Input.MouseEventHandler(this.GoalInvestmentDetailsVipHoverTarget_MouseEnter);
            
            #line default
            #line hidden
            
            #line 1662 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.GoalInvestmentDetailsVipHoverTarget.MouseLeave += new System.Windows.Input.MouseEventHandler(this.GoalInvestmentDetailsVipHoverTarget_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 65:
            this.GoalInvestmentDetailsVipGuidePopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 66:
            
            #line 1685 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Border)(target)).MouseEnter += new System.Windows.Input.MouseEventHandler(this.GoalInvestmentDetailsVipGuide_MouseEnter);
            
            #line default
            #line hidden
            
            #line 1686 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeave += new System.Windows.Input.MouseEventHandler(this.GoalInvestmentDetailsVipGuide_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 67:
            
            #line 1703 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.GoalInvestmentDetailsVipGuideOpenButton_Click);
            
            #line default
            #line hidden
            return;
            case 68:
            this.TrendTooltipPopup = ((System.Windows.Controls.Primitives.Popup)(target));
            
            #line 1726 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.TrendTooltipPopup.Closed += new System.EventHandler(this.TrendTooltipPopup_Closed);
            
            #line default
            #line hidden
            
            #line 1730 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.TrendTooltipPopup.Opened += new System.EventHandler(this.TrendTooltipPopup_Opened);
            
            #line default
            #line hidden
            return;
            case 69:
            this.GoalTrendTooltipPopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 70:
            this.MonthlyFocusTargetPopup = ((System.Windows.Controls.Primitives.Popup)(target));
            
            #line 1795 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.MonthlyFocusTargetPopup.Opened += new System.EventHandler(this.MonthlyFocusTargetPopup_Opened);
            
            #line default
            #line hidden
            return;
            case 71:
            this.MonthlyFocusTargetInputBox = ((System.Windows.Controls.TextBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 39:
            
            #line 1292 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.FocusRecord_Click);
            
            #line default
            #line hidden
            break;
            case 50:
            
            #line 1536 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.TextBox)(target)).IsVisibleChanged += new System.Windows.DependencyPropertyChangedEventHandler(this.GoalNameTextBox_IsVisibleChanged);
            
            #line default
            #line hidden
            
            #line 1536 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.TextBox)(target)).LostKeyboardFocus += new System.Windows.Input.KeyboardFocusChangedEventHandler(this.GoalNameTextBox_LostKeyboardFocus);
            
            #line default
            #line hidden
            
            #line 1536 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.TextBox)(target)).PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.GoalNameTextBox_PreviewKeyDown);
            
            #line default
            #line hidden
            break;
            case 51:
            
            #line 1543 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SaveGoalRenameButton_Click);
            
            #line default
            #line hidden
            break;
            case 62:
            
            #line 1628 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.FocusRecord_Click);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

