#pragma checksum "..\..\src\FocusApp.Desktop\Views\FocusRecordDetailsWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "E5392C8C0897E0C3ECB3608F0E3B599346CA1F43"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FocusApp.Desktop.Views {
    
    
    /// <summary>
    /// FocusRecordDetailsWindow
    /// </summary>
    public partial class FocusRecordDetailsWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 23 "..\..\src\FocusApp.Desktop\Views\FocusRecordDetailsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border PopoverBody;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\src\FocusApp.Desktop\Views\FocusRecordDetailsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.TranslateTransform PopoverOffset;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\src\FocusApp.Desktop\Views\FocusRecordDetailsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button MoreButton;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\src\FocusApp.Desktop\Views\FocusRecordDetailsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ContextMenu MoreMenu;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\src\FocusApp.Desktop\Views\FocusRecordDetailsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem DeleteButton;
        
        #line default
        #line hidden
        
        
        #line 90 "..\..\src\FocusApp.Desktop\Views\FocusRecordDetailsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock DeleteError;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/FocusApp.Desktop;component/views/focusrecorddetailswindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\src\FocusApp.Desktop\Views\FocusRecordDetailsWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 4 "..\..\src\FocusApp.Desktop\Views\FocusRecordDetailsWindow.xaml"
            ((FocusApp.Desktop.Views.FocusRecordDetailsWindow)(target)).PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.Window_KeyDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.PopoverBody = ((System.Windows.Controls.Border)(target));
            return;
            case 3:
            this.PopoverOffset = ((System.Windows.Media.TranslateTransform)(target));
            return;
            case 4:
            this.MoreButton = ((System.Windows.Controls.Button)(target));
            
            #line 36 "..\..\src\FocusApp.Desktop\Views\FocusRecordDetailsWindow.xaml"
            this.MoreButton.Click += new System.Windows.RoutedEventHandler(this.More_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.MoreMenu = ((System.Windows.Controls.ContextMenu)(target));
            
            #line 38 "..\..\src\FocusApp.Desktop\Views\FocusRecordDetailsWindow.xaml"
            this.MoreMenu.Closed += new System.Windows.RoutedEventHandler(this.MoreMenu_Closed);
            
            #line default
            #line hidden
            return;
            case 6:
            this.DeleteButton = ((System.Windows.Controls.MenuItem)(target));
            
            #line 42 "..\..\src\FocusApp.Desktop\Views\FocusRecordDetailsWindow.xaml"
            this.DeleteButton.Click += new System.Windows.RoutedEventHandler(this.Delete_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            
            #line 56 "..\..\src\FocusApp.Desktop\Views\FocusRecordDetailsWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Close_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.DeleteError = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

