#pragma checksum "..\..\src\FocusApp.Desktop\Views\FocusGoalSettingsModal.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "9B8B7D332AD0E862D0EA0CF742682F74ECA5EE1A"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FocusApp.Desktop.Views {
    
    
    /// <summary>
    /// FocusGoalSettingsModal
    /// </summary>
    public partial class FocusGoalSettingsModal : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 205 "..\..\src\FocusApp.Desktop\Views\FocusGoalSettingsModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border FocusGoalSettingsCard;
        
        #line default
        #line hidden
        
        
        #line 280 "..\..\src\FocusApp.Desktop\Views\FocusGoalSettingsModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button DailyFixedModeButton;
        
        #line default
        #line hidden
        
        
        #line 304 "..\..\src\FocusApp.Desktop\Views\FocusGoalSettingsModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button MonthlyTotalModeButton;
        
        #line default
        #line hidden
        
        
        #line 333 "..\..\src\FocusApp.Desktop\Views\FocusGoalSettingsModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel DailyFixedContent;
        
        #line default
        #line hidden
        
        
        #line 362 "..\..\src\FocusApp.Desktop\Views\FocusGoalSettingsModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox DailyTargetHoursInputBox;
        
        #line default
        #line hidden
        
        
        #line 390 "..\..\src\FocusApp.Desktop\Views\FocusGoalSettingsModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button EveryDayRepeatButton;
        
        #line default
        #line hidden
        
        
        #line 414 "..\..\src\FocusApp.Desktop\Views\FocusGoalSettingsModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button CustomRepeatButton;
        
        #line default
        #line hidden
        
        
        #line 479 "..\..\src\FocusApp.Desktop\Views\FocusGoalSettingsModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel MonthlyTotalContent;
        
        #line default
        #line hidden
        
        
        #line 508 "..\..\src\FocusApp.Desktop\Views\FocusGoalSettingsModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox MonthlyTargetHoursInputBox;
        
        #line default
        #line hidden
        
        
        #line 577 "..\..\src\FocusApp.Desktop\Views\FocusGoalSettingsModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button TargetSettingsCancelButton;
        
        #line default
        #line hidden
        
        
        #line 583 "..\..\src\FocusApp.Desktop\Views\FocusGoalSettingsModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button TargetSettingsSaveButton;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/FocusApp.Desktop;component/views/focusgoalsettingsmodal.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\src\FocusApp.Desktop\Views\FocusGoalSettingsModal.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 8 "..\..\src\FocusApp.Desktop\Views\FocusGoalSettingsModal.xaml"
            ((FocusApp.Desktop.Views.FocusGoalSettingsModal)(target)).PreviewMouseDown += new System.Windows.Input.MouseButtonEventHandler(this.FocusGoalSettingsModal_PreviewMouseDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.FocusGoalSettingsCard = ((System.Windows.Controls.Border)(target));
            return;
            case 3:
            this.DailyFixedModeButton = ((System.Windows.Controls.Button)(target));
            return;
            case 4:
            this.MonthlyTotalModeButton = ((System.Windows.Controls.Button)(target));
            return;
            case 5:
            this.DailyFixedContent = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 6:
            this.DailyTargetHoursInputBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 366 "..\..\src\FocusApp.Desktop\Views\FocusGoalSettingsModal.xaml"
            this.DailyTargetHoursInputBox.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TargetHoursInputBox_TextChanged);
            
            #line default
            #line hidden
            
            #line 367 "..\..\src\FocusApp.Desktop\Views\FocusGoalSettingsModal.xaml"
            this.DailyTargetHoursInputBox.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.TargetHoursInputBox_PreviewKeyDown);
            
            #line default
            #line hidden
            
            #line 368 "..\..\src\FocusApp.Desktop\Views\FocusGoalSettingsModal.xaml"
            this.DailyTargetHoursInputBox.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.TargetHoursInputBox_PreviewTextInput);
            
            #line default
            #line hidden
            
            #line 369 "..\..\src\FocusApp.Desktop\Views\FocusGoalSettingsModal.xaml"
            this.DailyTargetHoursInputBox.LostKeyboardFocus += new System.Windows.Input.KeyboardFocusChangedEventHandler(this.TargetHoursInputBox_LostKeyboardFocus);
            
            #line default
            #line hidden
            
            #line 370 "..\..\src\FocusApp.Desktop\Views\FocusGoalSettingsModal.xaml"
            this.DailyTargetHoursInputBox.AddHandler(System.Windows.DataObject.PastingEvent, new System.Windows.DataObjectPastingEventHandler(this.TargetHoursInputBox_Pasting));
            
            #line default
            #line hidden
            return;
            case 7:
            this.EveryDayRepeatButton = ((System.Windows.Controls.Button)(target));
            return;
            case 8:
            this.CustomRepeatButton = ((System.Windows.Controls.Button)(target));
            return;
            case 9:
            this.MonthlyTotalContent = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 10:
            this.MonthlyTargetHoursInputBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 512 "..\..\src\FocusApp.Desktop\Views\FocusGoalSettingsModal.xaml"
            this.MonthlyTargetHoursInputBox.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TargetHoursInputBox_TextChanged);
            
            #line default
            #line hidden
            
            #line 513 "..\..\src\FocusApp.Desktop\Views\FocusGoalSettingsModal.xaml"
            this.MonthlyTargetHoursInputBox.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.TargetHoursInputBox_PreviewKeyDown);
            
            #line default
            #line hidden
            
            #line 514 "..\..\src\FocusApp.Desktop\Views\FocusGoalSettingsModal.xaml"
            this.MonthlyTargetHoursInputBox.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.TargetHoursInputBox_PreviewTextInput);
            
            #line default
            #line hidden
            
            #line 515 "..\..\src\FocusApp.Desktop\Views\FocusGoalSettingsModal.xaml"
            this.MonthlyTargetHoursInputBox.LostKeyboardFocus += new System.Windows.Input.KeyboardFocusChangedEventHandler(this.TargetHoursInputBox_LostKeyboardFocus);
            
            #line default
            #line hidden
            
            #line 516 "..\..\src\FocusApp.Desktop\Views\FocusGoalSettingsModal.xaml"
            this.MonthlyTargetHoursInputBox.AddHandler(System.Windows.DataObject.PastingEvent, new System.Windows.DataObjectPastingEventHandler(this.TargetHoursInputBox_Pasting));
            
            #line default
            #line hidden
            return;
            case 11:
            this.TargetSettingsCancelButton = ((System.Windows.Controls.Button)(target));
            return;
            case 12:
            this.TargetSettingsSaveButton = ((System.Windows.Controls.Button)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

