#pragma checksum "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "88C67BAED0B1247A21009A508704BD1904C662DA"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FocusApp.Desktop.ViewModels;
using FocusApp.Desktop.Views;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FocusApp.Desktop.Views {
    
    
    /// <summary>
    /// StatisticsPage
    /// </summary>
    public partial class StatisticsPage : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 407 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border TodayStatisticsCard;
        
        #line default
        #line hidden
        
        
        #line 409 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid TodayFocusEmptyState;
        
        #line default
        #line hidden
        
        
        #line 432 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel TodayFocusSecondaryInfo;
        
        #line default
        #line hidden
        
        
        #line 444 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SetTodayFocusTargetButton;
        
        #line default
        #line hidden
        
        
        #line 458 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid TodayFocusTargetState;
        
        #line default
        #line hidden
        
        
        #line 498 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel TodayFocusTargetDetails;
        
        #line default
        #line hidden
        
        
        #line 508 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button TodayFocusTargetMoreButton;
        
        #line default
        #line hidden
        
        
        #line 549 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border TrendCard;
        
        #line default
        #line hidden
        
        
        #line 551 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid VipTrendContent;
        
        #line default
        #line hidden
        
        
        #line 564 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel TrendSummaryHeader;
        
        #line default
        #line hidden
        
        
        #line 610 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FocusApp.Desktop.Views.TrendChart TrendChartControl;
        
        #line default
        #line hidden
        
        
        #line 615 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid VipLockedPlaceholder;
        
        #line default
        #line hidden
        
        
        #line 630 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border TrendVipHoverTarget;
        
        #line default
        #line hidden
        
        
        #line 640 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid LockedTrendSkeletonChart;
        
        #line default
        #line hidden
        
        
        #line 677 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup TrendVipGuidePopup;
        
        #line default
        #line hidden
        
        
        #line 729 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border MonthlyFocusTargetCard;
        
        #line default
        #line hidden
        
        
        #line 731 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid MonthlyFocusTargetEmptyState;
        
        #line default
        #line hidden
        
        
        #line 744 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SetMonthlyFocusTargetButton;
        
        #line default
        #line hidden
        
        
        #line 750 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid MonthlyFocusTargetSetState;
        
        #line default
        #line hidden
        
        
        #line 778 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ProgressBar MonthlyFocusTargetProgressBar;
        
        #line default
        #line hidden
        
        
        #line 786 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock MonthlyFocusTargetPercent;
        
        #line default
        #line hidden
        
        
        #line 818 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button EditMonthlyFocusTargetButton;
        
        #line default
        #line hidden
        
        
        #line 836 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup MonthlyFocusTargetActionMenu;
        
        #line default
        #line hidden
        
        
        #line 863 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border CalendarAndDistributionContainer;
        
        #line default
        #line hidden
        
        
        #line 1003 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl GoalDistributionItemsControl;
        
        #line default
        #line hidden
        
        
        #line 1122 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border DailyFocusRecordCard;
        
        #line default
        #line hidden
        
        
        #line 1124 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid DailyFocusRecordContent;
        
        #line default
        #line hidden
        
        
        #line 1143 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid CalendarDayMetrics;
        
        #line default
        #line hidden
        
        
        #line 1174 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.ToggleButton CompletedTasksButton;
        
        #line default
        #line hidden
        
        
        #line 1227 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup CompletedTasksPopup;
        
        #line default
        #line hidden
        
        
        #line 1234 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CompletedTasksEmpty;
        
        #line default
        #line hidden
        
        
        #line 1235 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer CompletedTasksListScroll;
        
        #line default
        #line hidden
        
        
        #line 1273 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl CompletedTasksList;
        
        #line default
        #line hidden
        
        
        #line 1294 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer DailyDistributionScrollViewer;
        
        #line default
        #line hidden
        
        
        #line 1318 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer CalendarRecordsScrollViewer;
        
        #line default
        #line hidden
        
        
        #line 1376 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid DailyFocusRecordLockedPlaceholder;
        
        #line default
        #line hidden
        
        
        #line 1395 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border DailyFocusRecordVipHoverTarget;
        
        #line default
        #line hidden
        
        
        #line 1418 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer DailyFocusRecordLockedScrollViewer;
        
        #line default
        #line hidden
        
        
        #line 1466 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup DailyFocusRecordVipGuidePopup;
        
        #line default
        #line hidden
        
        
        #line 1518 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel GoalsPageLayout;
        
        #line default
        #line hidden
        
        
        #line 1524 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button GoalListMenuButton;
        
        #line default
        #line hidden
        
        
        #line 1596 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border GoalInvestmentDetailsCard;
        
        #line default
        #line hidden
        
        
        #line 1598 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GoalInvestmentDetailsContent;
        
        #line default
        #line hidden
        
        
        #line 1607 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.ToggleButton GoalDetailMoreButton;
        
        #line default
        #line hidden
        
        
        #line 1608 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup GoalDetailMorePopup;
        
        #line default
        #line hidden
        
        
        #line 1639 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer GoalProgressScrollViewer;
        
        #line default
        #line hidden
        
        
        #line 1641 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl GoalDateGroupsControl;
        
        #line default
        #line hidden
        
        
        #line 1692 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GoalInvestmentDetailsLockedPlaceholder;
        
        #line default
        #line hidden
        
        
        #line 1695 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border GoalInvestmentDetailsVipHoverTarget;
        
        #line default
        #line hidden
        
        
        #line 1702 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup GoalInvestmentDetailsVipGuidePopup;
        
        #line default
        #line hidden
        
        
        #line 1756 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup TrendTooltipPopup;
        
        #line default
        #line hidden
        
        
        #line 1784 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup GoalTrendTooltipPopup;
        
        #line default
        #line hidden
        
        
        #line 1822 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup MonthlyFocusTargetPopup;
        
        #line default
        #line hidden
        
        
        #line 1839 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox MonthlyFocusTargetInputBox;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/FocusApp.Desktop;component/views/statisticspage.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.TodayStatisticsCard = ((System.Windows.Controls.Border)(target));
            return;
            case 2:
            this.TodayFocusEmptyState = ((System.Windows.Controls.Grid)(target));
            return;
            case 3:
            this.TodayFocusSecondaryInfo = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 4:
            this.SetTodayFocusTargetButton = ((System.Windows.Controls.Button)(target));
            return;
            case 5:
            this.TodayFocusTargetState = ((System.Windows.Controls.Grid)(target));
            return;
            case 6:
            this.TodayFocusTargetDetails = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 7:
            this.TodayFocusTargetMoreButton = ((System.Windows.Controls.Button)(target));
            return;
            case 8:
            this.TrendCard = ((System.Windows.Controls.Border)(target));
            return;
            case 9:
            this.VipTrendContent = ((System.Windows.Controls.Grid)(target));
            return;
            case 10:
            this.TrendSummaryHeader = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 11:
            this.TrendChartControl = ((FocusApp.Desktop.Views.TrendChart)(target));
            return;
            case 12:
            this.VipLockedPlaceholder = ((System.Windows.Controls.Grid)(target));
            return;
            case 13:
            this.TrendVipHoverTarget = ((System.Windows.Controls.Border)(target));
            
            #line 630 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.TrendVipHoverTarget.MouseEnter += new System.Windows.Input.MouseEventHandler(this.TrendVipHoverTarget_MouseEnter);
            
            #line default
            #line hidden
            
            #line 630 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.TrendVipHoverTarget.MouseLeave += new System.Windows.Input.MouseEventHandler(this.TrendVipHoverTarget_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 14:
            this.LockedTrendSkeletonChart = ((System.Windows.Controls.Grid)(target));
            return;
            case 15:
            this.TrendVipGuidePopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 16:
            
            #line 693 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Border)(target)).MouseEnter += new System.Windows.Input.MouseEventHandler(this.TrendVipGuide_MouseEnter);
            
            #line default
            #line hidden
            
            #line 694 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeave += new System.Windows.Input.MouseEventHandler(this.TrendVipGuide_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 17:
            
            #line 711 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.TrendVipGuideOpenButton_Click);
            
            #line default
            #line hidden
            return;
            case 18:
            this.MonthlyFocusTargetCard = ((System.Windows.Controls.Border)(target));
            return;
            case 19:
            this.MonthlyFocusTargetEmptyState = ((System.Windows.Controls.Grid)(target));
            return;
            case 20:
            this.SetMonthlyFocusTargetButton = ((System.Windows.Controls.Button)(target));
            
            #line 744 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.SetMonthlyFocusTargetButton.PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.MonthlyFocusTargetAnchor_PreviewMouseLeftButtonDown);
            
            #line default
            #line hidden
            
            #line 744 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.SetMonthlyFocusTargetButton.Click += new System.Windows.RoutedEventHandler(this.SetMonthlyFocusTargetButton_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            this.MonthlyFocusTargetSetState = ((System.Windows.Controls.Grid)(target));
            return;
            case 22:
            this.MonthlyFocusTargetProgressBar = ((System.Windows.Controls.ProgressBar)(target));
            return;
            case 23:
            this.MonthlyFocusTargetPercent = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 24:
            this.EditMonthlyFocusTargetButton = ((System.Windows.Controls.Button)(target));
            
            #line 834 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.EditMonthlyFocusTargetButton.PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.MonthlyFocusTargetMenuButton_PreviewMouseLeftButtonDown);
            
            #line default
            #line hidden
            
            #line 835 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.EditMonthlyFocusTargetButton.Click += new System.Windows.RoutedEventHandler(this.MonthlyFocusTargetMenuButton_Click);
            
            #line default
            #line hidden
            return;
            case 25:
            this.MonthlyFocusTargetActionMenu = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 26:
            
            #line 849 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.EditMonthlyFocusTargetMenuItem_Click);
            
            #line default
            #line hidden
            return;
            case 27:
            
            #line 850 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.DeleteMonthlyFocusTargetMenuItem_Click);
            
            #line default
            #line hidden
            return;
            case 28:
            this.CalendarAndDistributionContainer = ((System.Windows.Controls.Border)(target));
            return;
            case 29:
            this.GoalDistributionItemsControl = ((System.Windows.Controls.ItemsControl)(target));
            return;
            case 30:
            this.DailyFocusRecordCard = ((System.Windows.Controls.Border)(target));
            return;
            case 31:
            this.DailyFocusRecordContent = ((System.Windows.Controls.Grid)(target));
            return;
            case 32:
            this.CalendarDayMetrics = ((System.Windows.Controls.Grid)(target));
            return;
            case 33:
            this.CompletedTasksButton = ((System.Windows.Controls.Primitives.ToggleButton)(target));
            
            #line 1174 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.CompletedTasksButton.PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.CompletedTasks_PreviewMouseLeftButtonDown);
            
            #line default
            #line hidden
            
            #line 1174 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.CompletedTasksButton.Click += new System.Windows.RoutedEventHandler(this.CompletedTasks_Click);
            
            #line default
            #line hidden
            return;
            case 34:
            this.CompletedTasksPopup = ((System.Windows.Controls.Primitives.Popup)(target));
            
            #line 1227 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.CompletedTasksPopup.Closed += new System.EventHandler(this.CompletedTasksPopup_Closed);
            
            #line default
            #line hidden
            return;
            case 35:
            
            #line 1228 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Border)(target)).KeyDown += new System.Windows.Input.KeyEventHandler(this.CompletedTasksPopup_KeyDown);
            
            #line default
            #line hidden
            return;
            case 36:
            this.CompletedTasksEmpty = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 37:
            this.CompletedTasksListScroll = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 38:
            this.CompletedTasksList = ((System.Windows.Controls.ItemsControl)(target));
            return;
            case 39:
            this.DailyDistributionScrollViewer = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 40:
            this.CalendarRecordsScrollViewer = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 42:
            this.DailyFocusRecordLockedPlaceholder = ((System.Windows.Controls.Grid)(target));
            return;
            case 43:
            this.DailyFocusRecordVipHoverTarget = ((System.Windows.Controls.Border)(target));
            
            #line 1398 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.DailyFocusRecordVipHoverTarget.MouseEnter += new System.Windows.Input.MouseEventHandler(this.DailyFocusRecordVipHoverTarget_MouseEnter);
            
            #line default
            #line hidden
            
            #line 1399 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.DailyFocusRecordVipHoverTarget.MouseLeave += new System.Windows.Input.MouseEventHandler(this.DailyFocusRecordVipHoverTarget_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 44:
            this.DailyFocusRecordLockedScrollViewer = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 45:
            this.DailyFocusRecordVipGuidePopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 46:
            
            #line 1482 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Border)(target)).MouseEnter += new System.Windows.Input.MouseEventHandler(this.DailyFocusRecordVipGuide_MouseEnter);
            
            #line default
            #line hidden
            
            #line 1483 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeave += new System.Windows.Input.MouseEventHandler(this.DailyFocusRecordVipGuide_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 47:
            
            #line 1500 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.DailyFocusRecordVipGuideOpenButton_Click);
            
            #line default
            #line hidden
            return;
            case 48:
            this.GoalsPageLayout = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 49:
            this.GoalListMenuButton = ((System.Windows.Controls.Button)(target));
            return;
            case 50:
            
            #line 1536 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SelectCurrentGoalListButton_Click);
            
            #line default
            #line hidden
            return;
            case 51:
            
            #line 1539 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SelectArchivedGoalListButton_Click);
            
            #line default
            #line hidden
            return;
            case 54:
            this.GoalInvestmentDetailsCard = ((System.Windows.Controls.Border)(target));
            return;
            case 55:
            this.GoalInvestmentDetailsContent = ((System.Windows.Controls.Grid)(target));
            return;
            case 56:
            this.GoalDetailMoreButton = ((System.Windows.Controls.Primitives.ToggleButton)(target));
            return;
            case 57:
            this.GoalDetailMorePopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 58:
            
            #line 1612 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.EditGoalButton_Click);
            
            #line default
            #line hidden
            return;
            case 59:
            
            #line 1613 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ArchiveGoalButton_Click);
            
            #line default
            #line hidden
            return;
            case 60:
            
            #line 1614 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.RestoreGoalButton_Click);
            
            #line default
            #line hidden
            return;
            case 61:
            
            #line 1615 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.DeleteGoalButton_Click);
            
            #line default
            #line hidden
            return;
            case 62:
            this.GoalProgressScrollViewer = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 63:
            this.GoalDateGroupsControl = ((System.Windows.Controls.ItemsControl)(target));
            return;
            case 65:
            this.GoalInvestmentDetailsLockedPlaceholder = ((System.Windows.Controls.Grid)(target));
            return;
            case 66:
            this.GoalInvestmentDetailsVipHoverTarget = ((System.Windows.Controls.Border)(target));
            
            #line 1695 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.GoalInvestmentDetailsVipHoverTarget.MouseEnter += new System.Windows.Input.MouseEventHandler(this.GoalInvestmentDetailsVipHoverTarget_MouseEnter);
            
            #line default
            #line hidden
            
            #line 1695 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.GoalInvestmentDetailsVipHoverTarget.MouseLeave += new System.Windows.Input.MouseEventHandler(this.GoalInvestmentDetailsVipHoverTarget_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 67:
            this.GoalInvestmentDetailsVipGuidePopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 68:
            
            #line 1718 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Border)(target)).MouseEnter += new System.Windows.Input.MouseEventHandler(this.GoalInvestmentDetailsVipGuide_MouseEnter);
            
            #line default
            #line hidden
            
            #line 1719 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeave += new System.Windows.Input.MouseEventHandler(this.GoalInvestmentDetailsVipGuide_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 69:
            
            #line 1736 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.GoalInvestmentDetailsVipGuideOpenButton_Click);
            
            #line default
            #line hidden
            return;
            case 70:
            this.TrendTooltipPopup = ((System.Windows.Controls.Primitives.Popup)(target));
            
            #line 1759 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.TrendTooltipPopup.Closed += new System.EventHandler(this.TrendTooltipPopup_Closed);
            
            #line default
            #line hidden
            
            #line 1763 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.TrendTooltipPopup.Opened += new System.EventHandler(this.TrendTooltipPopup_Opened);
            
            #line default
            #line hidden
            return;
            case 71:
            this.GoalTrendTooltipPopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 72:
            this.MonthlyFocusTargetPopup = ((System.Windows.Controls.Primitives.Popup)(target));
            
            #line 1828 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            this.MonthlyFocusTargetPopup.Opened += new System.EventHandler(this.MonthlyFocusTargetPopup_Opened);
            
            #line default
            #line hidden
            return;
            case 73:
            this.MonthlyFocusTargetInputBox = ((System.Windows.Controls.TextBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 41:
            
            #line 1325 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.FocusRecord_Click);
            
            #line default
            #line hidden
            break;
            case 52:
            
            #line 1569 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.TextBox)(target)).IsVisibleChanged += new System.Windows.DependencyPropertyChangedEventHandler(this.GoalNameTextBox_IsVisibleChanged);
            
            #line default
            #line hidden
            
            #line 1569 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.TextBox)(target)).LostKeyboardFocus += new System.Windows.Input.KeyboardFocusChangedEventHandler(this.GoalNameTextBox_LostKeyboardFocus);
            
            #line default
            #line hidden
            
            #line 1569 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.TextBox)(target)).PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.GoalNameTextBox_PreviewKeyDown);
            
            #line default
            #line hidden
            break;
            case 53:
            
            #line 1576 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SaveGoalRenameButton_Click);
            
            #line default
            #line hidden
            break;
            case 64:
            
            #line 1661 "..\..\src\FocusApp.Desktop\Views\StatisticsPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.FocusRecord_Click);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

