#pragma checksum "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "9C3742D5E9E7D5DFB9C0C22DB7E38A7DAC4D2DB6"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FocusApp.Desktop.Views {
    
    
    /// <summary>
    /// AuthModal
    /// </summary>
    public partial class AuthModal : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 127 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid LoginPanel;
        
        #line default
        #line hidden
        
        
        #line 209 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox LoginAccountTextBox;
        
        #line default
        #line hidden
        
        
        #line 258 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox LoginPasswordBox;
        
        #line default
        #line hidden
        
        
        #line 270 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox LoginPasswordTextBox;
        
        #line default
        #line hidden
        
        
        #line 305 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LoginPasswordVisibilityIcon;
        
        #line default
        #line hidden
        
        
        #line 365 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid PasswordRecoveryPanel;
        
        #line default
        #line hidden
        
        
        #line 399 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid RecoveryAccountStepPanel;
        
        #line default
        #line hidden
        
        
        #line 438 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox RecoveryAccountTextBox;
        
        #line default
        #line hidden
        
        
        #line 478 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid RecoveryVerificationStepPanel;
        
        #line default
        #line hidden
        
        
        #line 511 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox RecoveryCodeBox1;
        
        #line default
        #line hidden
        
        
        #line 512 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox RecoveryCodeBox2;
        
        #line default
        #line hidden
        
        
        #line 513 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox RecoveryCodeBox3;
        
        #line default
        #line hidden
        
        
        #line 514 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox RecoveryCodeBox4;
        
        #line default
        #line hidden
        
        
        #line 515 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox RecoveryCodeBox5;
        
        #line default
        #line hidden
        
        
        #line 516 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox RecoveryCodeBox6;
        
        #line default
        #line hidden
        
        
        #line 539 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid RecoveryNewPasswordStepPanel;
        
        #line default
        #line hidden
        
        
        #line 566 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox RecoveryNewPasswordBox;
        
        #line default
        #line hidden
        
        
        #line 567 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox RecoveryNewPasswordTextBox;
        
        #line default
        #line hidden
        
        
        #line 571 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock RecoveryNewPasswordVisibilityIcon;
        
        #line default
        #line hidden
        
        
        #line 578 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox RecoveryConfirmPasswordBox;
        
        #line default
        #line hidden
        
        
        #line 579 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox RecoveryConfirmPasswordTextBox;
        
        #line default
        #line hidden
        
        
        #line 583 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock RecoveryConfirmPasswordVisibilityIcon;
        
        #line default
        #line hidden
        
        
        #line 592 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid RecoveryCompletedStepPanel;
        
        #line default
        #line hidden
        
        
        #line 611 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid RegisterPanel;
        
        #line default
        #line hidden
        
        
        #line 799 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox RegisterPasswordBox;
        
        #line default
        #line hidden
        
        
        #line 809 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox RegisterPasswordTextBox;
        
        #line default
        #line hidden
        
        
        #line 842 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock RegisterPasswordVisibilityIcon;
        
        #line default
        #line hidden
        
        
        #line 863 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox RegisterConfirmPasswordBox;
        
        #line default
        #line hidden
        
        
        #line 873 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox RegisterConfirmPasswordTextBox;
        
        #line default
        #line hidden
        
        
        #line 906 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock RegisterConfirmPasswordVisibilityIcon;
        
        #line default
        #line hidden
        
        
        #line 919 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.ToggleButton RegisterAgreementCheckBox;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/FocusApp.Desktop;component/views/authmodal.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 125 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            ((System.Windows.Controls.Border)(target)).MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.AuthCard_MouseDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.LoginPanel = ((System.Windows.Controls.Grid)(target));
            return;
            case 3:
            this.LoginAccountTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            this.LoginPasswordBox = ((System.Windows.Controls.PasswordBox)(target));
            
            #line 268 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            this.LoginPasswordBox.PasswordChanged += new System.Windows.RoutedEventHandler(this.LoginPasswordBox_PasswordChanged);
            
            #line default
            #line hidden
            
            #line 269 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            this.LoginPasswordBox.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.LoginPasswordBox_PreviewKeyDown);
            
            #line default
            #line hidden
            return;
            case 5:
            this.LoginPasswordTextBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 279 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            this.LoginPasswordTextBox.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.LoginPasswordBox_PreviewKeyDown);
            
            #line default
            #line hidden
            return;
            case 6:
            
            #line 303 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ToggleLoginPasswordVisibility_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.LoginPasswordVisibilityIcon = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            
            #line 320 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.StartPasswordRecoveryButton_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.PasswordRecoveryPanel = ((System.Windows.Controls.Grid)(target));
            return;
            case 10:
            this.RecoveryAccountStepPanel = ((System.Windows.Controls.Grid)(target));
            return;
            case 11:
            this.RecoveryAccountTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 12:
            
            #line 469 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ContinueRecoveryButton_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.RecoveryVerificationStepPanel = ((System.Windows.Controls.Grid)(target));
            return;
            case 14:
            this.RecoveryCodeBox1 = ((System.Windows.Controls.TextBox)(target));
            
            #line 511 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            this.RecoveryCodeBox1.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.RecoveryCodeBox_TextChanged);
            
            #line default
            #line hidden
            
            #line 511 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            this.RecoveryCodeBox1.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.RecoveryCodeBox_PreviewKeyDown);
            
            #line default
            #line hidden
            
            #line 511 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            this.RecoveryCodeBox1.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.RecoveryCodeBox_PreviewTextInput);
            
            #line default
            #line hidden
            return;
            case 15:
            this.RecoveryCodeBox2 = ((System.Windows.Controls.TextBox)(target));
            
            #line 512 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            this.RecoveryCodeBox2.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.RecoveryCodeBox_TextChanged);
            
            #line default
            #line hidden
            
            #line 512 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            this.RecoveryCodeBox2.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.RecoveryCodeBox_PreviewKeyDown);
            
            #line default
            #line hidden
            
            #line 512 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            this.RecoveryCodeBox2.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.RecoveryCodeBox_PreviewTextInput);
            
            #line default
            #line hidden
            return;
            case 16:
            this.RecoveryCodeBox3 = ((System.Windows.Controls.TextBox)(target));
            
            #line 513 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            this.RecoveryCodeBox3.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.RecoveryCodeBox_TextChanged);
            
            #line default
            #line hidden
            
            #line 513 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            this.RecoveryCodeBox3.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.RecoveryCodeBox_PreviewKeyDown);
            
            #line default
            #line hidden
            
            #line 513 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            this.RecoveryCodeBox3.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.RecoveryCodeBox_PreviewTextInput);
            
            #line default
            #line hidden
            return;
            case 17:
            this.RecoveryCodeBox4 = ((System.Windows.Controls.TextBox)(target));
            
            #line 514 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            this.RecoveryCodeBox4.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.RecoveryCodeBox_TextChanged);
            
            #line default
            #line hidden
            
            #line 514 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            this.RecoveryCodeBox4.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.RecoveryCodeBox_PreviewKeyDown);
            
            #line default
            #line hidden
            
            #line 514 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            this.RecoveryCodeBox4.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.RecoveryCodeBox_PreviewTextInput);
            
            #line default
            #line hidden
            return;
            case 18:
            this.RecoveryCodeBox5 = ((System.Windows.Controls.TextBox)(target));
            
            #line 515 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            this.RecoveryCodeBox5.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.RecoveryCodeBox_TextChanged);
            
            #line default
            #line hidden
            
            #line 515 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            this.RecoveryCodeBox5.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.RecoveryCodeBox_PreviewKeyDown);
            
            #line default
            #line hidden
            
            #line 515 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            this.RecoveryCodeBox5.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.RecoveryCodeBox_PreviewTextInput);
            
            #line default
            #line hidden
            return;
            case 19:
            this.RecoveryCodeBox6 = ((System.Windows.Controls.TextBox)(target));
            
            #line 516 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            this.RecoveryCodeBox6.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.RecoveryCodeBox_TextChanged);
            
            #line default
            #line hidden
            
            #line 516 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            this.RecoveryCodeBox6.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.RecoveryCodeBox_PreviewKeyDown);
            
            #line default
            #line hidden
            
            #line 516 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            this.RecoveryCodeBox6.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.RecoveryCodeBox_PreviewTextInput);
            
            #line default
            #line hidden
            return;
            case 20:
            
            #line 522 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ResendRecoveryCodeButton_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            this.RecoveryNewPasswordStepPanel = ((System.Windows.Controls.Grid)(target));
            return;
            case 22:
            this.RecoveryNewPasswordBox = ((System.Windows.Controls.PasswordBox)(target));
            
            #line 566 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            this.RecoveryNewPasswordBox.PasswordChanged += new System.Windows.RoutedEventHandler(this.RecoveryNewPasswordBox_PasswordChanged);
            
            #line default
            #line hidden
            return;
            case 23:
            this.RecoveryNewPasswordTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 24:
            
            #line 571 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ToggleRecoveryNewPasswordVisibility_Click);
            
            #line default
            #line hidden
            return;
            case 25:
            this.RecoveryNewPasswordVisibilityIcon = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 26:
            this.RecoveryConfirmPasswordBox = ((System.Windows.Controls.PasswordBox)(target));
            
            #line 578 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            this.RecoveryConfirmPasswordBox.PasswordChanged += new System.Windows.RoutedEventHandler(this.RecoveryConfirmPasswordBox_PasswordChanged);
            
            #line default
            #line hidden
            return;
            case 27:
            this.RecoveryConfirmPasswordTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 28:
            
            #line 583 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ToggleRecoveryConfirmPasswordVisibility_Click);
            
            #line default
            #line hidden
            return;
            case 29:
            this.RecoveryConfirmPasswordVisibilityIcon = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 30:
            this.RecoveryCompletedStepPanel = ((System.Windows.Controls.Grid)(target));
            return;
            case 31:
            this.RegisterPanel = ((System.Windows.Controls.Grid)(target));
            return;
            case 32:
            this.RegisterPasswordBox = ((System.Windows.Controls.PasswordBox)(target));
            
            #line 808 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            this.RegisterPasswordBox.PasswordChanged += new System.Windows.RoutedEventHandler(this.RegisterPasswordBox_PasswordChanged);
            
            #line default
            #line hidden
            return;
            case 33:
            this.RegisterPasswordTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 34:
            
            #line 840 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ToggleRegisterPasswordVisibility_Click);
            
            #line default
            #line hidden
            return;
            case 35:
            this.RegisterPasswordVisibilityIcon = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 36:
            this.RegisterConfirmPasswordBox = ((System.Windows.Controls.PasswordBox)(target));
            
            #line 872 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            this.RegisterConfirmPasswordBox.PasswordChanged += new System.Windows.RoutedEventHandler(this.RegisterConfirmPasswordBox_PasswordChanged);
            
            #line default
            #line hidden
            return;
            case 37:
            this.RegisterConfirmPasswordTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 38:
            
            #line 904 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ToggleRegisterConfirmPasswordVisibility_Click);
            
            #line default
            #line hidden
            return;
            case 39:
            this.RegisterConfirmPasswordVisibilityIcon = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 40:
            
            #line 918 "..\..\src\FocusApp.Desktop\Views\AuthModal.xaml"
            ((System.Windows.Controls.StackPanel)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.RegisterAgreementRow_MouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 41:
            this.RegisterAgreementCheckBox = ((System.Windows.Controls.Primitives.ToggleButton)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

