#pragma checksum "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "891D438C35041799DF74403336F081220D622A1E"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FocusApp.Desktop.Views;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FocusApp.Desktop.Views {
    
    
    /// <summary>
    /// FocusFlowView
    /// </summary>
    public partial class FocusFlowView : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 291 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image NoTaskFocusBackground;
        
        #line default
        #line hidden
        
        
        #line 329 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid TargetFocusingView;
        
        #line default
        #line hidden
        
        
        #line 512 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FocusApp.Desktop.Views.FocusTaskWindow TaskPopupView;
        
        #line default
        #line hidden
        
        
        #line 524 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid NoTaskFocusingView;
        
        #line default
        #line hidden
        
        
        #line 603 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid TargetCompletionView;
        
        #line default
        #line hidden
        
        
        #line 619 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image TargetCompletionBackground;
        
        #line default
        #line hidden
        
        
        #line 627 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image TargetCompletionRibbon;
        
        #line default
        #line hidden
        
        
        #line 776 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border SessionCompletedTasksPopup;
        
        #line default
        #line hidden
        
        
        #line 790 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer SessionCompletedTasksScrollViewer;
        
        #line default
        #line hidden
        
        
        #line 855 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid NoTargetCompletionView;
        
        #line default
        #line hidden
        
        
        #line 871 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image NoTargetCompletionBackground;
        
        #line default
        #line hidden
        
        
        #line 879 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image NoTargetCompletionRibbon;
        
        #line default
        #line hidden
        
        
        #line 887 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock NoTargetCompletionTitle;
        
        #line default
        #line hidden
        
        
        #line 909 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border NoTargetCompletionSummary;
        
        #line default
        #line hidden
        
        
        #line 984 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border FocusEndConfirmationDialog;
        
        #line default
        #line hidden
        
        
        #line 1005 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image FocusEndConfirmationClock;
        
        #line default
        #line hidden
        
        
        #line 1030 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock FocusEndElapsedValue;
        
        #line default
        #line hidden
        
        
        #line 1033 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border FocusEndShortWarning;
        
        #line default
        #line hidden
        
        
        #line 1040 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock FocusEndDiscardHintText;
        
        #line default
        #line hidden
        
        
        #line 1043 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel FocusEndNormalStatus;
        
        #line default
        #line hidden
        
        
        #line 1049 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock FocusEndSaveHintText;
        
        #line default
        #line hidden
        
        
        #line 1053 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid FocusEndShortActions;
        
        #line default
        #line hidden
        
        
        #line 1055 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button FocusDiscardConfirmationButton;
        
        #line default
        #line hidden
        
        
        #line 1058 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button FocusShortContinueConfirmationButton;
        
        #line default
        #line hidden
        
        
        #line 1062 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid FocusEndNormalActions;
        
        #line default
        #line hidden
        
        
        #line 1064 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button FocusContinueConfirmationButton;
        
        #line default
        #line hidden
        
        
        #line 1067 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button FocusEndConfirmationButton;
        
        #line default
        #line hidden
        
        
        #line 1088 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border FocusAgainConfirmationDialog;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/FocusApp.Desktop;component/views/focusflowview.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.NoTaskFocusBackground = ((System.Windows.Controls.Image)(target));
            return;
            case 2:
            
            #line 314 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
            ((System.Windows.Controls.Grid)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.TitleBar_MouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 3:
            
            #line 317 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.MinimizeButton_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            
            #line 322 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CloseButton_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.TargetFocusingView = ((System.Windows.Controls.Grid)(target));
            
            #line 331 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
            this.TargetFocusingView.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.TargetMode_MouseDown);
            
            #line default
            #line hidden
            return;
            case 6:
            
            #line 493 "..\..\src\FocusApp.Desktop\Views\FocusFlowView.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ViewTasksButton_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.TaskPopupView = ((FocusApp.Desktop.Views.FocusTaskWindow)(target));
            return;
            case 8:
            this.NoTaskFocusingView = ((System.Windows.Controls.Grid)(target));
            return;
            case 9:
            this.TargetCompletionView = ((System.Windows.Controls.Grid)(target));
            return;
            case 10:
            this.TargetCompletionBackground = ((System.Windows.Controls.Image)(target));
            return;
            case 11:
            this.TargetCompletionRibbon = ((System.Windows.Controls.Image)(target));
            return;
            case 12:
            this.SessionCompletedTasksPopup = ((System.Windows.Controls.Border)(target));
            return;
            case 13:
            this.SessionCompletedTasksScrollViewer = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 14:
            this.NoTargetCompletionView = ((System.Windows.Controls.Grid)(target));
            return;
            case 15:
            this.NoTargetCompletionBackground = ((System.Windows.Controls.Image)(target));
            return;
            case 16:
            this.NoTargetCompletionRibbon = ((System.Windows.Controls.Image)(target));
            return;
            case 17:
            this.NoTargetCompletionTitle = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 18:
            this.NoTargetCompletionSummary = ((System.Windows.Controls.Border)(target));
            return;
            case 19:
            this.FocusEndConfirmationDialog = ((System.Windows.Controls.Border)(target));
            return;
            case 20:
            this.FocusEndConfirmationClock = ((System.Windows.Controls.Image)(target));
            return;
            case 21:
            this.FocusEndElapsedValue = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 22:
            this.FocusEndShortWarning = ((System.Windows.Controls.Border)(target));
            return;
            case 23:
            this.FocusEndDiscardHintText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 24:
            this.FocusEndNormalStatus = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 25:
            this.FocusEndSaveHintText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 26:
            this.FocusEndShortActions = ((System.Windows.Controls.Grid)(target));
            return;
            case 27:
            this.FocusDiscardConfirmationButton = ((System.Windows.Controls.Button)(target));
            return;
            case 28:
            this.FocusShortContinueConfirmationButton = ((System.Windows.Controls.Button)(target));
            return;
            case 29:
            this.FocusEndNormalActions = ((System.Windows.Controls.Grid)(target));
            return;
            case 30:
            this.FocusContinueConfirmationButton = ((System.Windows.Controls.Button)(target));
            return;
            case 31:
            this.FocusEndConfirmationButton = ((System.Windows.Controls.Button)(target));
            return;
            case 32:
            this.FocusAgainConfirmationDialog = ((System.Windows.Controls.Border)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

