//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/audio/focus.mp3")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/icons/targets/analytics.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/icons/targets/brain.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/icons/targets/chemistry.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/icons/targets/code.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/icons/targets/design.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/icons/targets/finance.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/icons/targets/first_aid.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/icons/targets/fitness.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/icons/targets/folder.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/icons/targets/gardening.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/icons/targets/geography.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/icons/targets/graduation.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/icons/targets/heart.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/icons/targets/internet.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/icons/targets/justice.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/icons/targets/kettlebell.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/icons/targets/medical.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/icons/targets/meditation.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/icons/targets/movies.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/icons/targets/music.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/icons/targets/notebook.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/icons/targets/painting.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/icons/targets/pets.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/icons/targets/reading.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/icons/targets/study.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/icons/targets/terminal.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/icons/targets/tools.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/icons/targets/travel.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/icons/targets/work.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("assets/icons/targets/writing.png")]


