#pragma checksum "..\..\src\FocusApp.Desktop\Views\CreateGoalModal.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "5AAD903592A70AFECAE7021C89E78A933562079B"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FocusApp.Desktop.Views {
    
    
    /// <summary>
    /// CreateGoalModal
    /// </summary>
    public partial class CreateGoalModal : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 109 "..\..\src\FocusApp.Desktop\Views\CreateGoalModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid CreateGoalDialogOverlay;
        
        #line default
        #line hidden
        
        
        #line 115 "..\..\src\FocusApp.Desktop\Views\CreateGoalModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border DialogCard;
        
        #line default
        #line hidden
        
        
        #line 159 "..\..\src\FocusApp.Desktop\Views\CreateGoalModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox NewGoalNameTextBox;
        
        #line default
        #line hidden
        
        
        #line 188 "..\..\src\FocusApp.Desktop\Views\CreateGoalModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button GoalIconLibraryButton;
        
        #line default
        #line hidden
        
        
        #line 231 "..\..\src\FocusApp.Desktop\Views\CreateGoalModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup GoalIconLibraryPopup;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/FocusApp.Desktop;component/views/creategoalmodal.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\src\FocusApp.Desktop\Views\CreateGoalModal.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 7 "..\..\src\FocusApp.Desktop\Views\CreateGoalModal.xaml"
            ((FocusApp.Desktop.Views.CreateGoalModal)(target)).PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.Modal_PreviewKeyDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.CreateGoalDialogOverlay = ((System.Windows.Controls.Grid)(target));
            
            #line 112 "..\..\src\FocusApp.Desktop\Views\CreateGoalModal.xaml"
            this.CreateGoalDialogOverlay.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.Overlay_MouseDown);
            
            #line default
            #line hidden
            return;
            case 3:
            this.DialogCard = ((System.Windows.Controls.Border)(target));
            return;
            case 4:
            this.NewGoalNameTextBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 167 "..\..\src\FocusApp.Desktop\Views\CreateGoalModal.xaml"
            this.NewGoalNameTextBox.IsVisibleChanged += new System.Windows.DependencyPropertyChangedEventHandler(this.NewGoalNameTextBox_IsVisibleChanged);
            
            #line default
            #line hidden
            
            #line 168 "..\..\src\FocusApp.Desktop\Views\CreateGoalModal.xaml"
            this.NewGoalNameTextBox.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.NewGoalNameTextBox_PreviewKeyDown);
            
            #line default
            #line hidden
            return;
            case 5:
            this.GoalIconLibraryButton = ((System.Windows.Controls.Button)(target));
            return;
            case 6:
            this.GoalIconLibraryPopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

