#pragma checksum "..\src\FocusApp.Agent\TrayPopupWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "6720E14EFD8136F1FB395E0129E277EF7157C6AC"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FocusApp.Agent {
    
    
    /// <summary>
    /// TrayPopupWindow
    /// </summary>
    public partial class TrayPopupWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 109 "..\src\FocusApp.Agent\TrayPopupWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border StatusPill;
        
        #line default
        #line hidden
        
        
        #line 114 "..\src\FocusApp.Agent\TrayPopupWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock StatusText;
        
        #line default
        #line hidden
        
        
        #line 120 "..\src\FocusApp.Agent\TrayPopupWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TimerText;
        
        #line default
        #line hidden
        
        
        #line 128 "..\src\FocusApp.Agent\TrayPopupWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock IdleHint;
        
        #line default
        #line hidden
        
        
        #line 139 "..\src\FocusApp.Agent\TrayPopupWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BlockingButton;
        
        #line default
        #line hidden
        
        
        #line 198 "..\src\FocusApp.Agent\TrayPopupWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TodayText;
        
        #line default
        #line hidden
        
        
        #line 244 "..\src\FocusApp.Agent\TrayPopupWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ExitButton;
        
        #line default
        #line hidden
        
        
        #line 254 "..\src\FocusApp.Agent\TrayPopupWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ExitIcon;
        
        #line default
        #line hidden
        
        
        #line 265 "..\src\FocusApp.Agent\TrayPopupWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ExitText;
        
        #line default
        #line hidden
        
        
        #line 270 "..\src\FocusApp.Agent\TrayPopupWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ExitHint;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/FocusApp.Agent;component/traypopupwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\src\FocusApp.Agent\TrayPopupWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.StatusPill = ((System.Windows.Controls.Border)(target));
            return;
            case 2:
            this.StatusText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.TimerText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.IdleHint = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.BlockingButton = ((System.Windows.Controls.Button)(target));
            
            #line 141 "..\src\FocusApp.Agent\TrayPopupWindow.xaml"
            this.BlockingButton.Click += new System.Windows.RoutedEventHandler(this.BlockingButton_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.TodayText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            
            #line 208 "..\src\FocusApp.Agent\TrayPopupWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OpenDesktopButton_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.ExitButton = ((System.Windows.Controls.Button)(target));
            
            #line 246 "..\src\FocusApp.Agent\TrayPopupWindow.xaml"
            this.ExitButton.Click += new System.Windows.RoutedEventHandler(this.ExitButton_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.ExitIcon = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.ExitText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.ExitHint = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

