<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseSystemDrawing>true</UseSystemDrawing>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FocusApp.Core\FocusApp.Core.csproj" />
    <ProjectReference Include="..\FocusApp.Contracts\FocusApp.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.104.2" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.7" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="8.0.8" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Audio\focus.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Icons\Common\Home_Shield.png" />
    <Resource Include="Assets\Icons\Common\Log_Out.png" />
    <Resource Include="Assets\Icons\Common\Menber_skin.png" />
    <Resource Include="Assets\Icons\Common\Menber_vip.png" />
    <Resource Include="Assets\Icons\Common\shiguang_logo.png" />
    <Resource Include="Assets\Icons\Common\vip_logo.png" />
    <Resource Include="Assets\Icons\Common\CompletePop-up_CheckBox.png" />
    <Resource Include="Assets\Images\Illustrations\create-target.png" />
    <Resource Include="Assets\Images\Illustrations\UserAvatar.png" />
    <Resource Include="Assets\Images\Illustrations\MemberCenter_Background.png" />
    <Resource Include="Assets\Images\Illustrations\MemberCenter_Crown.png" />
    <Resource Include="Assets\Images\Illustrations\MenberCenter_check.png" />
    <Resource Include="Assets\Images\Illustrations\foucusOntheEnd_ribbon.png" />
    <Resource Include="Assets\Themes\Solid\Orange\sidebar-logo.png" />
    <Resource Include="Assets\Themes\Solid\Orange\foucus_background.png" />
    <Resource Include="Assets\Themes\Solid\Orange\foucusOntheEnd_ribbon.png" />
    <Resource Include="Assets\Themes\Solid\Orange\gantanhao.png" />
    <Resource Include="Assets\Themes\Solid\Orange\gouxuan.png" />
    <Resource Include="Assets\Themes\Solid\Orange\shizhong.png" />
    <Resource Include="Assets\Themes\Solid\Orange\shizhong_white.png" />
    <Resource Include="Assets\Themes\Solid\Orange\suo.png" />
    <Resource Include="Assets\Themes\Solid\Orange\zhankai.png" />
    <Resource Include="Assets\Themes\Solid\Orange\focusPage_OrangeLine.png" />
    <Resource Include="Assets\Themes\Solid\Orange\mubiao.png" />
    <Resource Include="Assets\Themes\Solid\Orange\renwugaunli.png" />
    <Resource Include="Assets\Themes\Solid\Orange\toast_gouxuan.png" />
    <Resource Include="Assets\Themes\Solid\Orange\toast_tixing.png" />
    <Resource Include="Assets\Themes\Solid\Orange\toast_jinggao.png" />
    <Resource Include="Assets\font\SourceHanSerifCN-Light-Subset.otf" />
    <Resource Include="Assets\font\SourceHanSerifCN-Regular-Subset.otf" />
    <Resource Include="Assets\font\SourceHanSerifCN-Medium-Subset.otf" />
  </ItemGroup>
</Project>
