#pragma checksum "..\..\src\FocusApp.Desktop\Views\CustomTimeModal.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "7D7EE45BF84E022077095E23929D875755C9ACF3"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FocusApp.Desktop.Views {
    
    
    /// <summary>
    /// CustomTimeModal
    /// </summary>
    public partial class CustomTimeModal : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 185 "..\..\src\FocusApp.Desktop\Views\CustomTimeModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox MinutesTextBox;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/FocusApp.Desktop;component/views/customtimemodal.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\src\FocusApp.Desktop\Views\CustomTimeModal.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.MinutesTextBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 197 "..\..\src\FocusApp.Desktop\Views\CustomTimeModal.xaml"
            this.MinutesTextBox.AddHandler(System.Windows.DataObject.PastingEvent, new System.Windows.DataObjectPastingEventHandler(this.MinutesTextBox_Pasting));
            
            #line default
            #line hidden
            
            #line 198 "..\..\src\FocusApp.Desktop\Views\CustomTimeModal.xaml"
            this.MinutesTextBox.IsVisibleChanged += new System.Windows.DependencyPropertyChangedEventHandler(this.MinutesTextBox_IsVisibleChanged);
            
            #line default
            #line hidden
            
            #line 199 "..\..\src\FocusApp.Desktop\Views\CustomTimeModal.xaml"
            this.MinutesTextBox.KeyDown += new System.Windows.Input.KeyEventHandler(this.MinutesTextBox_KeyDown);
            
            #line default
            #line hidden
            
            #line 200 "..\..\src\FocusApp.Desktop\Views\CustomTimeModal.xaml"
            this.MinutesTextBox.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.MinutesTextBox_PreviewTextInput);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

