#pragma checksum "..\..\src\FocusApp.Desktop\Views\FocusTargetModal.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "0DBF214B4B445E7BBF45D2B587A877EA81CB7932"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FocusApp.Desktop.Views {
    
    
    /// <summary>
    /// FocusTargetModal
    /// </summary>
    public partial class FocusTargetModal : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 334 "..\..\src\FocusApp.Desktop\Views\FocusTargetModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button TargetModalCloseButton;
        
        #line default
        #line hidden
        
        
        #line 457 "..\..\src\FocusApp.Desktop\Views\FocusTargetModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid NewTaskEntryRow;
        
        #line default
        #line hidden
        
        
        #line 459 "..\..\src\FocusApp.Desktop\Views\FocusTargetModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid NewTaskEditorContainer;
        
        #line default
        #line hidden
        
        
        #line 460 "..\..\src\FocusApp.Desktop\Views\FocusTargetModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox NewTaskTextBox;
        
        #line default
        #line hidden
        
        
        #line 633 "..\..\src\FocusApp.Desktop\Views\FocusTargetModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid EmptyTargetState;
        
        #line default
        #line hidden
        
        
        #line 680 "..\..\src\FocusApp.Desktop\Views\FocusTargetModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid CreateTargetPlusGlyph;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/FocusApp.Desktop;component/views/focustargetmodal.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\src\FocusApp.Desktop\Views\FocusTargetModal.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 6 "..\..\src\FocusApp.Desktop\Views\FocusTargetModal.xaml"
            ((FocusApp.Desktop.Views.FocusTargetModal)(target)).PreviewMouseDown += new System.Windows.Input.MouseButtonEventHandler(this.FocusTargetModal_PreviewMouseDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.TargetModalCloseButton = ((System.Windows.Controls.Button)(target));
            return;
            case 3:
            
            #line 439 "..\..\src\FocusApp.Desktop\Views\FocusTargetModal.xaml"
            ((System.Windows.Controls.ScrollViewer)(target)).ScrollChanged += new System.Windows.Controls.ScrollChangedEventHandler(this.TaskScrollViewer_ScrollChanged);
            
            #line default
            #line hidden
            return;
            case 4:
            this.NewTaskEntryRow = ((System.Windows.Controls.Grid)(target));
            return;
            case 5:
            this.NewTaskEditorContainer = ((System.Windows.Controls.Grid)(target));
            return;
            case 6:
            this.NewTaskTextBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 462 "..\..\src\FocusApp.Desktop\Views\FocusTargetModal.xaml"
            this.NewTaskTextBox.IsVisibleChanged += new System.Windows.DependencyPropertyChangedEventHandler(this.Editor_IsVisibleChanged);
            
            #line default
            #line hidden
            
            #line 463 "..\..\src\FocusApp.Desktop\Views\FocusTargetModal.xaml"
            this.NewTaskTextBox.KeyDown += new System.Windows.Input.KeyEventHandler(this.NewTaskTextBox_KeyDown);
            
            #line default
            #line hidden
            
            #line 464 "..\..\src\FocusApp.Desktop\Views\FocusTargetModal.xaml"
            this.NewTaskTextBox.LostKeyboardFocus += new System.Windows.Input.KeyboardFocusChangedEventHandler(this.NewTaskTextBox_LostKeyboardFocus);
            
            #line default
            #line hidden
            return;
            case 11:
            this.EmptyTargetState = ((System.Windows.Controls.Grid)(target));
            return;
            case 12:
            this.CreateTargetPlusGlyph = ((System.Windows.Controls.Grid)(target));
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 7:
            
            #line 499 "..\..\src\FocusApp.Desktop\Views\FocusTargetModal.xaml"
            ((System.Windows.Controls.Border)(target)).MouseEnter += new System.Windows.Input.MouseEventHandler(this.TaskRow_MouseEnter);
            
            #line default
            #line hidden
            
            #line 500 "..\..\src\FocusApp.Desktop\Views\FocusTargetModal.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeave += new System.Windows.Input.MouseEventHandler(this.TaskRow_MouseLeave);
            
            #line default
            #line hidden
            break;
            case 8:
            
            #line 568 "..\..\src\FocusApp.Desktop\Views\FocusTargetModal.xaml"
            ((System.Windows.Controls.TextBox)(target)).IsVisibleChanged += new System.Windows.DependencyPropertyChangedEventHandler(this.Editor_IsVisibleChanged);
            
            #line default
            #line hidden
            
            #line 569 "..\..\src\FocusApp.Desktop\Views\FocusTargetModal.xaml"
            ((System.Windows.Controls.TextBox)(target)).KeyDown += new System.Windows.Input.KeyEventHandler(this.EditTaskTextBox_KeyDown);
            
            #line default
            #line hidden
            
            #line 570 "..\..\src\FocusApp.Desktop\Views\FocusTargetModal.xaml"
            ((System.Windows.Controls.TextBox)(target)).LostKeyboardFocus += new System.Windows.Input.KeyboardFocusChangedEventHandler(this.EditTaskTextBox_LostKeyboardFocus);
            
            #line default
            #line hidden
            break;
            case 9:
            
            #line 609 "..\..\src\FocusApp.Desktop\Views\FocusTargetModal.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.EditTaskButton_Click);
            
            #line default
            #line hidden
            break;
            case 10:
            
            #line 616 "..\..\src\FocusApp.Desktop\Views\FocusTargetModal.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.DeleteTaskButton_Click);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

