#pragma checksum "..\..\src\FocusApp.Desktop\Views\AccountSyncModal.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "986A8C5700D53CEEE745385ABE1996ECF2CF7DC1"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FocusApp.Desktop.ViewModels;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FocusApp.Desktop.Views {
    
    
    /// <summary>
    /// AccountSyncModal
    /// </summary>
    public partial class AccountSyncModal : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 246 "..\..\src\FocusApp.Desktop\Views\AccountSyncModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer ContentScrollViewer;
        
        #line default
        #line hidden
        
        
        #line 271 "..\..\src\FocusApp.Desktop\Views\AccountSyncModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel CloudSectionAnchor;
        
        #line default
        #line hidden
        
        
        #line 333 "..\..\src\FocusApp.Desktop\Views\AccountSyncModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel DevicesSectionAnchor;
        
        #line default
        #line hidden
        
        
        #line 426 "..\..\src\FocusApp.Desktop\Views\AccountSyncModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel SecuritySectionAnchor;
        
        #line default
        #line hidden
        
        
        #line 536 "..\..\src\FocusApp.Desktop\Views\AccountSyncModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox PasswordVerificationCodeTextBox;
        
        #line default
        #line hidden
        
        
        #line 590 "..\..\src\FocusApp.Desktop\Views\AccountSyncModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox AccountNewPasswordBox;
        
        #line default
        #line hidden
        
        
        #line 598 "..\..\src\FocusApp.Desktop\Views\AccountSyncModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox AccountNewPasswordTextBox;
        
        #line default
        #line hidden
        
        
        #line 608 "..\..\src\FocusApp.Desktop\Views\AccountSyncModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock AccountNewPasswordVisibilityIcon;
        
        #line default
        #line hidden
        
        
        #line 633 "..\..\src\FocusApp.Desktop\Views\AccountSyncModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox AccountConfirmPasswordBox;
        
        #line default
        #line hidden
        
        
        #line 641 "..\..\src\FocusApp.Desktop\Views\AccountSyncModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox AccountConfirmPasswordTextBox;
        
        #line default
        #line hidden
        
        
        #line 651 "..\..\src\FocusApp.Desktop\Views\AccountSyncModal.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock AccountConfirmPasswordVisibilityIcon;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/FocusApp.Desktop;component/views/accountsyncmodal.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\src\FocusApp.Desktop\Views\AccountSyncModal.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 7 "..\..\src\FocusApp.Desktop\Views\AccountSyncModal.xaml"
            ((FocusApp.Desktop.Views.AccountSyncModal)(target)).IsVisibleChanged += new System.Windows.DependencyPropertyChangedEventHandler(this.AccountSyncModal_IsVisibleChanged);
            
            #line default
            #line hidden
            return;
            case 2:
            
            #line 181 "..\..\src\FocusApp.Desktop\Views\AccountSyncModal.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NavigationButton_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            
            #line 202 "..\..\src\FocusApp.Desktop\Views\AccountSyncModal.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NavigationButton_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            
            #line 223 "..\..\src\FocusApp.Desktop\Views\AccountSyncModal.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NavigationButton_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.ContentScrollViewer = ((System.Windows.Controls.ScrollViewer)(target));
            
            #line 251 "..\..\src\FocusApp.Desktop\Views\AccountSyncModal.xaml"
            this.ContentScrollViewer.PreviewMouseWheel += new System.Windows.Input.MouseWheelEventHandler(this.ContentScrollViewer_PreviewMouseWheel);
            
            #line default
            #line hidden
            
            #line 252 "..\..\src\FocusApp.Desktop\Views\AccountSyncModal.xaml"
            this.ContentScrollViewer.ScrollChanged += new System.Windows.Controls.ScrollChangedEventHandler(this.ContentScrollViewer_ScrollChanged);
            
            #line default
            #line hidden
            return;
            case 6:
            this.CloudSectionAnchor = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 7:
            this.DevicesSectionAnchor = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 8:
            this.SecuritySectionAnchor = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 9:
            
            #line 454 "..\..\src\FocusApp.Desktop\Views\AccountSyncModal.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OpenPasswordChange_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            this.PasswordVerificationCodeTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 11:
            this.AccountNewPasswordBox = ((System.Windows.Controls.PasswordBox)(target));
            
            #line 597 "..\..\src\FocusApp.Desktop\Views\AccountSyncModal.xaml"
            this.AccountNewPasswordBox.PasswordChanged += new System.Windows.RoutedEventHandler(this.AccountNewPasswordBox_PasswordChanged);
            
            #line default
            #line hidden
            return;
            case 12:
            this.AccountNewPasswordTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 13:
            
            #line 607 "..\..\src\FocusApp.Desktop\Views\AccountSyncModal.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ToggleAccountNewPasswordVisibility_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            this.AccountNewPasswordVisibilityIcon = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 15:
            this.AccountConfirmPasswordBox = ((System.Windows.Controls.PasswordBox)(target));
            
            #line 640 "..\..\src\FocusApp.Desktop\Views\AccountSyncModal.xaml"
            this.AccountConfirmPasswordBox.PasswordChanged += new System.Windows.RoutedEventHandler(this.AccountConfirmPasswordBox_PasswordChanged);
            
            #line default
            #line hidden
            return;
            case 16:
            this.AccountConfirmPasswordTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 17:
            
            #line 650 "..\..\src\FocusApp.Desktop\Views\AccountSyncModal.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ToggleAccountConfirmPasswordVisibility_Click);
            
            #line default
            #line hidden
            return;
            case 18:
            this.AccountConfirmPasswordVisibilityIcon = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

